<?php
 /* Attempt at my first Live grid! */
include('../../config/settings.inc.php');
include("$nwnpath/include/locs.inc.php");
$locs = new Locations();

$HEADEXTRA = "<script type=\"text/javascript\" src=\"". BASEURL ."/ext/adapter/ext/ext-base.js\"></script>
<script type=\"text/javascript\" src=\"". BASEURL ."/ext/ext-all.js\"></script>
<link rel=\"stylesheet\" type=\"text/css\" href=\"". BASEURL ."/ext/resources/css/ext-all.css\" />";
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>SchoolNet8 | Live DataGrid</title>
<?php echo $HEADEXTRA; ?>
 <style type="text/css" media="screen">@import "<?php echo BASEURL; ?>/css/main.css";</style>
 <style type="text/css" media="print">@import "<?php echo BASEURL; ?>/css/print
css";</style>
  <script type="text/javascript" src="<?php echo BASEURL; ?>/js/common.js?v=102"></script>
  <style type="text/css">
    html, body {
        margin:0;
        padding:0;
        border:0 none;
        overflow:hidden;
        height:100%;
    }
  </style>
</head>
<body>
<div id="north">
<div id="imgbar">
<?php
  echo '<a href="'. BASEURL .'tool/clicktru.php?station=CIPCO" target="_new"><img src="'. BASEURL .'/pics/CIPCO.png" alt="Banner" border="0"/></a><a href="'. BASEURL .'/tool/clicktru.php?station=TOUCH" target="_new"><img src="'. BASEURL .'/pics/banner2.gif" alt="Banner" border="0"/></a>';
?></div>

<ul id="linkbar">
 <li class="<?php if ($THISPAGE == "homepage") echo "selected"; ?>"><a href="<?php echo BASEURL; ?>">Home</a></li>
 <li class="<?php if ($THISPAGE == "mysite") echo "selected"; ?>"><a href="<?php echo BASEURL; ?>/site.phtml">My Site</a></li>
 <li class="<?php if ($THISPAGE == "current") echo "selected"; ?>"><a href="<?php echo BASEURL; ?>/current.phtml">Currents</a></li>
 <li class="<?php if ($THISPAGE == "download") echo "selected"; ?>"><a href="<?php echo BASEURL; ?>/dl/index.phtml">Download</a></li>
 <li class="<?php if ($THISPAGE == "siteindex") echo "selected"; ?>"><a href="<?php echo BASEURL; ?>/guide/siteindex.phtml">Site Index</a></li>
 <li class="<?php if ($THISPAGE == "training") echo "selected"; ?>"><a href="<?php echo BASEURL; ?>/training/">Training</a></li>
 <li class="<?php if ($THISPAGE == "webcam") echo "selected"; ?>"><a href="<?php echo BASEURL; ?>/camera/index.phtml">WebCams</a></li>
</ul>
This application will refresh automatically, you can click on the headings to sort the data.
</div>
<div id="south">
<p>SchoolNet8.com sponsored by: <a href="<?php echo BASEURL; ?>/tool/clicktru.php?station=KCCI" target="_new" class="ftext">CIPCO</a>
&nbsp; &nbsp; Page Loaded: <?php echo date("d F Y  h:i A"); ?> [<a href="<?php echo BASEURL; ?>/contact.phtml">Contact Info</a>]</p>
</div>
<script>
Ext.onReady(function(){
    var obstore = new Ext.data.Store({
          root:'ugcs',
          autoLoad:true,
          sortInfo: {field: "i", direction: "ASC"},
          proxy: new Ext.data.HttpProxy({
                url: '/json/get-json',
                method: 'GET'
          }),
          reader: new Ext.data.JsonReader({
            root: 'data',
            id: 'i'
           }, [
           {name: 'i'},
           {name: 't'},
           {name: 'd'},
           {name: 's'},
           {name: 'r'},
           {name: 'h'},
           {name: 'l'},
           {name: 'p'},
           {name: 'x'},
           {name: 'm'}
          ])

        });

    var grid = new Ext.grid.GridPanel({
        id:'obgrid',
        store: obstore,
        cm: new Ext.grid.ColumnModel([
         {header: "Site", align:'left', width: 175,renderer: sitename, sortable: true, dataIndex: 'i'},
         {header: "Time", width: 150, sortable: true, dataIndex: 'm'},
         {header: "Temp", sortable: true, dataIndex: 't'},
         {header: "Dew Point", sortable: true, dataIndex: 'd'},
         {header: "Wind Speed", sortable: true, dataIndex: 's'},
         {header: "Wind Gust", sortable: true, dataIndex: 'x'},
         {header: "Wind Dir", sortable: true, dataIndex: 'r'},
         {header: "High Temp", sortable: true, dataIndex: 'h'},
         {header: "Low Temp", sortable: true, dataIndex: 'l'},
         {header: "Rainfall", sortable: true, dataIndex: 'p'}
        ]),
        viewConfig: { forceFit:true},
        stripeRows: true,
        title:'Live Observations',
        autoScroll:true
    });

  var siteLookup = new Ext.util.MixedCollection();
<?php
reset($locs->table);
while( list($id,$d) = each($locs->table) )
{
  echo "siteLookup.add('$id', \"". $d['city'] ."\");";
}
?>

 function sitename(val) {
  if (siteLookup.indexOfKey(val) < 0) return val;
  return siteLookup.get(val);
 }

  var task = {
    run: function(){
        obstore.reload();
    },
    interval: 15000 
  }
  Ext.TaskMgr.start(task);
  

  var viewport = new Ext.Viewport({
    layout:'border',
    items:[
       new Ext.BoxComponent({ // raw
                    region:'north',
                    el: 'north',
                    height:100
       }), 
       new Ext.BoxComponent({ // raw
                    region:'south',
                    el: 'south',
                    height:40
       }), 
      {region:'center',
       items: grid,
       layout:'fit'}
      ]
  });

  var scrollTop = 0;
  obstore.on('beforeload', function(){
    scrollTop = (grid.rendered)
        ? grid.view.scroller.dom.scrollTop
        : 0;
  });
  obstore.on('load', function(){
    grid.view.scroller.scroll('down', scrollTop, true);
  });  

});

</script>
</body>
</html>
