<p><strong>Sites that explain wind barbs:</strong>
<ul>
 <li><a href="http://ww2010.atmos.uiuc.edu/(Gh)/guides/maps/sfcobs/wnd.rxml">WW2010 Illinois</a></li>
 <li><a href="http://www.rap.ucar.edu/weather/info/about_windbarb.html">NCAR RAP</a></li>
</ul>

<p><strong>Other sites:</strong>
<ul>
 <li><a 
href="http://ww2010.atmos.uiuc.edu/(Gh)/guides/mtr/af/adv/cadv.rxml">Cold 
Air Advection</a> [Illinois]</li>
</ul>
