<p><img src="barbs/wind_barb.gif" style="float: left;"> Atmospheric winds 
are often represented on weather maps in the form of a wind barb.  Wind 
barb symbols give information about wind speed and wind direction in one 
symbol.  The goal of this lesson is to teach you how to read wind barbs.

<p>Wind barbs are composed of two components.  The first is a flag pole 
which indicates direction.  The second is a number of flags on the end of 
this flagpole which represents wind speeds.  Commonly, the units for wind 
speed are expressed in knots, which is 1 nautical mile per hour.  (1 knot 
= 1.15 mph)

<p>The image shown on the side can be found at the UCAR site linked below.  
It gives an overview about how much each flag is worth and how to compute 
the wind speed.  If you are still confused, there are other links below 
with more information on wind barbs.

<br clear="all" />

