<ol>

<li>Open an archived Iowa Mesonet map from <a target="_new"
href="http://mesonet.agron.iastate.edu/archive/data/2005/01/02/mesonet_1300.gif">January 
2nd, 2005 at 7am.</a>  The area shown on this plot is the state of Iowa.  
This map is called a surface plot, since it displays surface 
weather information.  Each reporting station has a number of symbols 
clustered around it.  Given the knowledge you have learned about wind 
barbs, from which direction is the wind mainly blowing from?</li>

<li>The wind barbs also give us information about the wind speeds.  
Looking at the same map, can you tell what the wind speeds are at various 
locations in Iowa?</li>

<li>The combination of wind speed and direction gives us an idea about 
where air is being moved around.  The same plot gives us temperatures, 
which are shown in red.  Can you guess if the temperatures in Central Iowa 
will be getting colder or warmer based solely on the wind and the 
temperature distribution in Iowa?</li>

</ol>

<h4>Possible Answers:</h4>

<ol>

<li>For the most part, winds are from the northwest.  This means if you 
stood at some location and faced to the northwest, the wind would be in 
your face.</li>

<li>Wind speeds are around 5 to 10 knots, which is roughly 5 to 10 
miles per hour.</li>

<li>The plot indicates much colder air in Northwest Iowa with temperatures 
around 10 degrees, while warmer air exists in Eastern Iowa with 
temperatures in the mid 30s. Given the northwest flow of air, one 
would expect the temperature to decline in Central Iowa.  
Meteorologists call this process cold air advection.</li>

</ol>
