<div class="urllink">
<img src="<?php echo $baseurl; ?>/images/redhat-web-browser.png">
<h5>Online @ SchoolNet8.com</h5>
<code><a
href="javascript:new_window_big('<?php echo $baseurl; 
?>/GIS/apps/plotter/currents.php');">Live Super Doppler8 App</a></code>

<p class="details">This application has many features to give you the 
ability to generate maps of current and historical weather in Iowa.  You 
can customize the area, time, plot variables, and other data layers all 
within one application!</p>

</div>

