<div class="urllink">
<img src="<?php echo $baseurl; ?>/images/redhat-web-browser.png">
<h5>Online @ SchoolNet8.com</h5>
<code><a
href="<?php echo $baseurl; ?>/site.phtml">My SchoolNet8 Site</a></code>

<p class="details">This page provides you with the most recent weather
observations from your SchoolNet8 site, along with links to other
custom information.  If the site currently displayed on this application
is not your location, you can change to your site by changing the site
name in the pull down menu on the lower right side of the page.  You could
also select your site from a map by following the <b>'Select from map'</b>
link.</p>
 </div>

