<div class="urllink">
<img src="<?php echo $baseurl; ?>/images/redhat-web-browser.png">
<h5>Online @ SchoolNet8.com</h5>
<code><a
href="<?php echo $baseurl; ?>/plotting/1trace_fe.phtml">1 minute data
traces</a></code>

<p class="details">This page allows you to view a graph of SchoolNet8
weather variables and how they change throughout the day.  This resource
can be found as a link called 'Plot Data Timeseries' from your SchoolNet8
site's homepage.</p>

</div>

