<div class="urllink">
<img src="<?php echo BASEURL; ?>/images/redhat-web-browser.png">
<h5>Online @ Schoolnet8.com</h5>
<code><a href="<?php echo BASEURL; ?>/cc.phtml">Sortable Currents</a></code>

<p class="details">This application allows you to quickly look at observations
from all the SchoolNet8 sites at once.  You can sort each variable in an
ascending or decending manner by clicking on the arrows below each column
heading.</p>
</div>

