<div class="urllink"> <img src="<?php echo $baseurl;
?>/images/redhat-web-browser.png"> <h5>Online @ Schoolnet8.com</h5>
<code><a href="<?php echo $baseurl; ?>/camera/viewer.phtml">Webcam Live
Images</a></code> <p class="details">This application requires high
bandwidth connections due to the size of the images downloaded.  You
simply pick the site you wish to view and click 'Live Shot'.  The
application actually connects to the camera and gives you a truely live
shot from the location.</p> </div>

