<div class="urllink"> <img src="<?php echo BASEURL;
?>/images/redhat-web-browser.png"> <h5>Online @ SchoolNet8.com</h5>
<code><a href="<?php echo BASEURL; ?>/camera/bloop.phtml">Webcam
historical loops</a></code>

<p class="details">The use of this application is mostly straight forward.
The first box gives you a listing of webcamera sites and when their
archive begins.  You can then set the beginning time and the number of
frames to display.  If you pick a large number, it may slow down your
browser significantly.</p>
</div>

