<?php
 include_once("../../config/settings.inc.php");
?>
<html>
<head>
	<title>KCCI SchoolNet8 @ The Iowa State Fair</title>
	<link rel="stylesheet" type="text/css" href="<?php echo $baseurl; ?>/css/main.css">
</head>
<body bgcolor="#f0f0f0">

<?php
  $app = 15;
  $station = "S03I4";
  include("$nwnpath/include/bar.inc.php");
?>
<div id="justone">
<table width="100%" align="left">
<tr>
<td colspan="2">
<a href="http://www.iowastatefair.com"><img src="2003logo175.gif" border=0 width="100" align="left"></a>
<font size="+2"><b>KCCI SchoolNet8 @ The Iowa State Fair</b></font>

<p>Thanks to the sponsorship of <a href="<?php echo $baseurl; ?>tool/clicktru.php?station=S03I4">Dynamic Broadband</a>, KCCI has added a <a href="<?php echo $baseurl; ?>">SchoolNet8</a> site at the Iowa State Fair!

</td></tr>
<tr><td width="50%" valign="TOP">

<p>The SchoolNet8 site at the Iowa State Fair has been removed 
following the conclusion of the fair.  Here is a listing of the 
<b>unofficial</b> daily climate summaries from the SchoolNet8 
site.

<table border=1>
<tr>
 <th>Date:</th><td>High:</td><td>Low:</td><td>Rainfall:</td><td>Attendance [1]</td></tr>

<tr><th>04 Aug 2003</th><td>81</td><td>68</td><td>0.00</td><td>-</td></tr>
<tr><th>05 Aug 2003</th><td>77</td><td>65</td><td>0.08</td><td>-</td></tr>
<tr><th>06 Aug 2003</th><td>82</td><td>65</td><td>0.00</td><td>-</td></tr>
<tr><th>07 Aug 2003</th><td>85</td><td>64</td><td>0.00</td><td>77,856</td></tr>
<tr><th>08 Aug 2003</th><td>84</td><td>64</td><td>0.00</td><td>96,709</td></tr>
<tr><th>09 Aug 2003</th><td>84</td><td>63</td><td>0.00</td><td>107,190</td></tr>
<tr><th>10 Aug 2003</th><td>83</td><td>64</td><td>0.04</td><td>87,222</td></tr>
<tr><th>11 Aug 2003</th><td>84</td><td>65</td><td>0.00</td><td>78,530</td></tr>
<tr><th>12 Aug 2003</th><td>78</td><td>63</td><td>0.02</td><td>88,052</td></tr>
<tr><th>13 Aug 2003</th><td>81</td><td>64</td><td>0.00</td><td>88,211</td></tr>
<tr><th>14 Aug 2003</th><td>82</td><td>66</td><td>0.00</td><td>89,243</td></tr>
<tr><th>15 Aug 2003</th><td>92</td><td>69</td><td>0.00</td><td>91,121</td></tr>
<tr><th>16 Aug 2003</th><td>97</td><td>71</td><td>0.00</td><td>92,018</td></tr>
<tr><th>17 Aug 2003</th><td>95</td><td>74</td><td>0.00</td><td>83,866</td></tr>
<tr><th>18 Aug 2003</th><td>95</td><td>74</td><td>0.00</td><td>-</td></tr>
<tr><th>19 Aug 2003</th><td>89</td><td>74</td><td>0.00</td><td>-</td></tr>
<tr><th>20 Aug 2003</th><td>97</td><td>75</td><td>0.00</td><td>-</td></tr>
<tr><th>21 Aug 2003</th><td>90</td><td>70</td><td>0.00</td><td>-</td></tr>
</table>

<p>[1] <a href="http://www.iowastatefair.com/attendance.html">http://www.iowastatefair.com/attendance.html</a>, viewed 26 Aug 2003

</td><td width="50%" valign="TOP">

<p><b>Last Web Camera Shot:</b> &nbsp; [<a href="../camera/bloop.phtml">View Past Images</a>]<br>
<img src="http://mesonet.agron.iastate.edu/data/camera/stills/S03I4.jpg" border=1>

</td></tr>
</table>
</div>
<?php 
  include("$nwnpath/include/footer.inc.php"); ?>
