<p>The goal of this lession is to explore the one minute data tracing 
application on the SchoolNet8.com website.  This application provides the 
ability to explore current and historical data at a very fine 
resolution in time.</p>

<p>Variations in the weather take place on different 'time scales', or 
time periods over which the variations take place.  Variations over long 
periods of time are called climate, while variations that occur in time 
periods shorter than 24 hours are typically described as weather. The 1 
minute data plotter allows us to look closely at patterns that occur 
during the daily weather cycle.</p>

