<ol>

<li>From your SchoolNet site homepage, click on the 'Plot Data Timeseries' 
link found under the 'Site Resources' heading.  You will be shown plots 
valid for today from your site.  Take a look at the temperature trace (red 
line in the first plot).  What can you say about how temperatures have 
changed for today?</li>

<li>How does the dew point (blue line in the first plot) trace compare 
with the temperature trace?  Does the dew point change as much as the 
temperature during the day?</li>

<li>In the <a href="index.phtml?module=solar">Solar Radiation</a> lesson, 
we discussed how solar radiation can effect temperature.  Do you see any 
impact of radiation on temperature for today?</li>

<li>Look at the wind data trace.  Which direction occured 
the most often during today?  If your answer is a northerly direction, 
have temperatures cooled considerably?</li>

<li>Take a look at the pressure trace.  A good rule of thumb for Iowa is 
that every 4 millibars of pressure change can support 10 MPH winds.  
For example, if they pressure changed by 16 millibars for today, one would 
expect 
winds of roughly 40 MPH for parts of the day.  Can you see signs of this 
rule of thumb on today's chart?</li>

<li>The storms on the morning of July 10th 2002 were extremely strong.  
Check out the <a 
href="<?php echo $baseurl; ?>/plotting/1trace_fe.phtml?station=SGLI4&year=2002&month=7&day=10" 
target="_new">1 
minute trace for Glidden</a> on this day.  From the charts, can you 
determine when the strongest storm hit the area?  From the three charts, 
describe what happened during this storm.</li>

</ol>

<h4>Possible Answers</h4>

<ol>

<li>In general, you should note an increase in temperature during the day 
and cooling at night.  Sometimes fronts and precipitation can alter this 
normal cycle.  If there are alterations in this normal cycle, can you 
explain what caused them?</li>

<li>Dew point must always be lower than or equal to the temperature.  
Dew Point is 
the value when the air is 100% saturated, which means that the air can not 
hold any more water vapor.  In general, the dew point does not vary much 
throughout the day.  While the temperature increases, the actual moisture 
content remains mostly the same.  If you notice changes, it is probably 
because of evaporation, moisture advection, or perhaps a faulty 
sensor.</li>

<li>The effect of solar radiation on temperature will vary from season to 
season and be modified by other conditions.  In general, an increase in 
radiation should lead to an increase in temperature.  If this did not 
happen, can you guess as to why?</li>

<li>You can determine the main wind direction by looking at which 
direction has the majority of the blue dots.  This will vary day to 
day with the passing weather systems.</li>

<li>The pressure trace should give you an indication on how windy it was 
during the day.  Large changes in pressure imply stronger
winds.  Winds 
are generated from horizontal differences in pressure, so if there is a 
large pressure change during the day, one would expect a strong winds as 
well.</li>

<li>The July 10th 2002 storm was an amazing storm.  The Glidden SchoolNet8 
site got absolutely slammed by a dangerous storm right at 7 AM in the 
morning.  Each plot indicates a different effect of what happened from 
this storm.  The temperature plot shows the sudden decrease in temperature 
associated with the rain cooled air being dropped by the thunderstorm.  
The wind plot shows the rapid and intense winds that occured at this time.  
While not shown on this plot, a peak gust of 96 MPH was measured at the 
site!  The most impressive plot is the last one.  Notice the 8 milibar 
increase in pressure with 2 inches of rain that rapidly fell from this 
storm.  Meteorologists refer to this storm as a downburst.  Downbursts are 
caused by a thunderstorm that rapidly decays and slams a small pocket of 
very cold air to the ground which then spreads out causing straight line 
wind damage.</li>

</ol>
