<p>Weather variables such as temperature, dew point, wind, and rainfall 
can vary with both space and time.  Scientists have shown that rainfall 
can significantly vary over distances as short as 3 feet!  Sites within 
the SchoolNet8 network measure all of the weather variables mentioned 
above.  Your SchoolNet8 site is located close to some other sites, yet 
relatively far away from other sites.  The purpose of this lesson is see 
how we can use SchoolNet8 data to see how weather differs from place to 
place.</p>
