<ol>

<li>For our first question, we will compare your site's weather data to a 
site nearby.  From your <i>My SchoolNet8 Site</i> page, select another 
site in the SchoolNet8 network by choosing it from the pull-down menu 
found near the lower righthand side of the page.  Be sure to click the 
'Compare Station' box to ensure that the comparison is made.  What 
differences do you notice in variables like temperature?</li>

<li>Many factors can influence temperatures reported by your SchoolNet8 
site.  Here are a few:
 <ul>

<li><b>Clouds</b> tend to prevent temperatures from warming during the day 
by restricting the amount of solar energy that reaches the ground.  They 
also tend to keep temperatures warmer at night by providing a blanket to 
prevent heat from escaping into space.</li>

<li><b>Winds</b> can bring warmer or colder air into Iowa by a process 
called advection.  By moving warmer or colder air into the state, it can 
locally raise or lower our temperatures.  For Iowans, we know that 
winds from the north tend to bring colder air into the state and winds 
from the south bring warmer air.  You can probably remember a cold 
winter day with a strong Northwest wind.</li>

<li><b>Snow cover</b>: Sites with snow cover versus sites without snow 
cover can produce different temperatures during the daytime and nighttime. 
Snow acts to reflect solar energy away from the Earth's surface during the 
day, which keeps us colder. At night, this colder daytime temperature 
combined with the long winter nights result in even colder nighttime 
temperatures.</li>

<li><b>Elevation</b>:  Although not that important in Iowa, differences in 
elevation, or height above sea level, can lead to differences in air 
temperatures.  This often occurs during the early evening and overnight.  
Cold air is more dense than warm air, so it tends to sink to lower 
elevations.  A site located in a valley compared with a site
on a hill will often have cooler temperatures at night, yet have similar
temperatures during the day.</li>

<li><b>Rainfall</b>:  Especially during 
the summer, locations that recieve rainfall during the day will be 
cooler than those without rain.  Rainfall cools the air by evaporating as 
it falls from the clouds.</li> 

<li><b>Urban Areas</b> are often warmer 
than rural areas during the day and night.  All of the buildings, 
concrete, and human activity tend to trap heat in the urban areas during 
the day 
and night.  This is commonly called a 'Urban Heat Island'.</li> 

</ul> 

<br />Looking at the above list. Can you guess which factors are 
contributing to any differences you are noticing with your 
comparison?</li>

<li>Do you notice any differences when you compare your site to sites near 
to you and when you compare against sites far away?</li>

</ol>

<h4>Possible Answers:</h4>

<ol>

<li>Differences in any weather variable will depend on when you make the 
comparison.  In general, differences should exist during windier and 
sunnier days.</li>

<li>The cause of these differences will be highly dependent on the day you 
are making the comparison.  If a difference seems too large to believe, it 
may be due to an error with one of the sensors.</li>

<li>In general, the differences in weather variables should increase with 
distance between the observing sensors.  Variables like solar radiation 
and precipitation can be highly variable over short distances.</li>

</ol>
