<html>
<head>
  <title>KCCI SchoolNet8 WebSite Admin</title>
  <link rel="stylesheet" type="text/css" href="../css/main.css">
</head>
<body bgcolor="white">

<table width="100%">
<tr><td align="CENTER"><img src="/kcci/pics/kcci_CIPCO.gif"></td></tr>
<tr bgcolor="#0000FF">
  <th><font color="#ffffff">SchoolNet8 Administrator</font></th></tr>
</table>

<p>Welcome to the schoolNet8 website administrator.  If you can't find 
what you need here, please let us know!</p>

<p><font class="bluet">Applications:</font><br>
  <li><a href="all_stats.phtml">Site Access Stats</a>
    <br>Tables and charts of website access statistics.</li>
  <li><a href="sponsorPDF.php">This month's stats in PDF format</a>
    <br>Custom Report for this month.</li>
</p>

<p><font class="bluet">News:</font><br>
 
 <li><b>28 Feb 2003:</b>  The correct date now appears on the stats
 <li><b>26 Dec 2002:</b>  Added the new Admin PDF printer...</li>
 <li><b>2 Dec 2002:</b>  Our official launch date!  Are you excitied!</li>

<p><font class="bluet">Previous Month Reports:</font><br>
 <li><a href="reports/kcciStats_0212.pdf">Dec 2002</a></li>
 <li><a href="reports/kcciStats_0301.pdf">Jan 2003</a></li>
 <li><a href="reports/kcciStats_0302.pdf">Feb 2003</a></li>
 <li><a href="reports/kcciStats_0303.pdf">Mar 2003</a></li>
 <li><a href="reports/kcciStats_0304.pdf">Apr 2003</a></li>
 <li><a href="reports/kcciStats_0305.pdf">May 2003</a></li>
 <li><a href="reports/kcciStats_0306.pdf">Jun 2003</a></li>
 <li><a href="reports/kcciStats_0307.pdf">Jul 2003</a></li>
 <li><a href="reports/kcciStats_0308.pdf">Aug 2003</a></li>
 <li><a href="reports/kcciStats_0309.pdf">Sep 2003</a></li>
 <li><a href="reports/kcciStats_0310.pdf">Oct 2003</a></li>

<p><font class="bluet">Contact Information:</font><br>

<br>Daryl Herzmann (<a href="mailto:akrherz@iastate.edu">akrherz@iastate.edu</a>)
<br>24hr Mesonet Hotline: 515.451.9249

</body>
</html>

