<?php
  /** sum.phtml
   */
?>

<td bgcolor="#ffadad" colspan=3>

<form method="GET" action="sum_worker.php">

You have selected daily summary data download.<br>

<table>
<tr>
  <th>Select Station:</th>
  <td>
<?php echo kcciSelect($station); ?>
  </td>
</tr>

<tr>
  <th>Select <a href="params.phtml">Parameters</a></th>
  <td>
     <table>
     <tr>
       <td><input type="checkbox" name="vars[]" value="max_tmpf">High Temperature</td>
       <td><input type="checkbox" name="vars[]" value="min_tmpf">Low Temperature</td>
     </tr>
     <tr>
       <td><input type="checkbox" name="vars[]" value="pday">Daily Rain</td>
       <td><input type="checkbox" name="vars[]" value="max_gust">Wind Gust [MPH]</td>
     </tr>
     <tr>
       <td><input type="checkbox" name="vars[]" value="max_drct">Wind Gust Direction</td>
       <td><input type="checkbox" name="vars[]" value="max_gust_ts">Time of Wind Gust</td>
     </tr>
     </table>
  </td>
</tr>

<tr>
  <th>Time Interval:</th>
  <td>
    <table>
     <tr>
      <td></td>
      <th>Year:</th>
      <th>Month:</th>
      <th>Day:</th>
     </tr>
     <tr>
      <th>Start:</th>
      <th rowspan=2>
<select name="year">
  <option value="2002">2002
  <option value="2003">2003
  <option value="2004">2004
  <option value="2005" SELECTED>2005
</select>
      </th>
      <td>
<select name="s_month">
  <option value="1">January
  <option value="2">February
  <option value="3">March
  <option value="4">April
  <option value="5">May
  <option value="6">June
  <option value="7">July
  <option value="8">August
  <option value="9">September
  <option value="10">October
  <option value="11">November
  <option value="12">December
</select>
      </td>
      <td>
<select name="s_day">
<?php
  for ($i=1; $i<32; $i++){
    echo "<option value=\"".$i."\">".$i ."\n";
  }
?>
</select>
</td>
     </tr>
     <tr>
      <th>End:</th>
      <td>
<select name="e_month">
  <option value="1">January
  <option value="2">February
  <option value="3">March
  <option value="4">April
  <option value="5">May
  <option value="6">June
  <option value="7">July
  <option value="8">August
  <option value="9">September
  <option value="10">October
  <option value="11">November
  <option value="12">December
</select>
      </td>
      <td>
<select name="e_day">
<?php
  for ($i=1; $i<32; $i++){
    echo "<option value=\"".$i."\">".$i ."\n";
  }
?>
</select>
      </td>
     </tr>
    </table>
  </td>
</tr>

<tr>
  <th>Download Options</th>
  <td>
   <select name="dl_option">
    <option value="download">Download to disk
    <option value="view">View on-line
   </select>
  </td>
</tr>

<tr>
  <th>Delimitation</th>
  <td>
   <select name="delim">
    <option value="comma">Comma
    <option value="space">Space
    <option value="tab">Tab
   </select>
  </tr>
</tr>

<tr>
  <td colspan="2" align="CENTER">
  <input type="submit" value="Download Data">
  <input type="reset">
</td>
</tr>

</table>

</form>
