<?php
  /** sum.phtml
   */
?>

<td bgcolor="#ffadad" colspan=3>

<form method="GET" action="sum_worker.php">

You have selected daily summary data download.<br>

<table>
<tr>
  <th>Select Station:</th>
  <td>
<?php echo kcciSelect(""); ?>
  </td>
</tr>

<tr>
  <th>Select <a href="params.phtml">Parameters</a></th>
  <td>
     <table>
     <tr>
       <td><input type="checkbox" name="vars[]" value="max_tmpf">High Temperature</td>
       <td><input type="checkbox" name="vars[]" value="min_tmpf">Low Temperature</td>
     </tr>
     <tr>
       <td><input type="checkbox" name="vars[]" value="pday">Daily Rain</td>
       <td><input type="checkbox" name="vars[]" value="max_gust">Wind Gust [MPH]</td>
     </tr>
     <tr>
       <td><input type="checkbox" name="vars[]" value="max_drct">Wind Gust Direction</td>
       <td><input type="checkbox" name="vars[]" value="max_gust_ts">Time of Wind Gust</td>
     </tr>
     </table>
  </td>
</tr>

<tr>
  <th>Time Interval:</th>
  <td>
    <table>
     <tr>
      <td></td>
      <th>Year:</th>
      <th>Month:</th>
      <th>Day:</th>
     </tr>
     <tr>
      <th>Start:</th>
      <th>
<?php echo yearSelect(2003, date("Y"), "s_year"); ?>
      </th>
      <td>
<?php echo monthSelect(date("m"), "s_month"); ?>
      </td>
      <td>
<?php echo daySelect(date("d"), "s_day"); ?>
</td>
     </tr>
     <tr>
      <th>End:</th>
      <th>
<?php echo yearSelect(2003, date("Y"), "e_year"); ?>
      </th>
      <td>
<?php echo monthSelect(date("m"), "e_month"); ?>
      </td>
      <td>
<?php echo daySelect(date("d"), "e_day"); ?>
</td>
     </tr>
    </table>
  </td>
</tr>

<tr>
  <th>Download Options</th>
  <td>
   <select name="dl_option">
    <option value="download">Download to disk
    <option value="view">View on-line
   </select>
  </td>
</tr>

<tr>
  <th>Delimitation</th>
  <td>
   <select name="delim">
    <option value="comma">Comma
    <option value="space">Space
    <option value="tab">Tab
   </select>
  </tr>
</tr>

<tr>
  <td colspan="2" align="CENTER">
  <input type="submit" value="Download Data">
  <input type="reset">
</td>
</tr>

</table>

</form>
