<p>SchoolNet8.com contains a handy application called 'Sortable Currents'.  
You can find this resource here:

<?php include("links/sortable.phtml"); ?>

<p>This application has the ability to sort any of the observation 
variables by clicking on one of the arrows underneath the column headings.  
The downward pointing arrow will sort values in a descending manner and 
the upward pointing arrow will sort values in a ascending manner.</p>

<p>At any time, you can click on the name of a SchoolNet8 site and get a 
graphical view of the current conditions for your site.  This application 
will open in a new window and refresh at an interval of your choice.</p>

<p>The page contains the current conditions for all 60+ sites in the 
SchoolNet8 network.  This listing can be a bit large to comprehend.  With 
that in mind, you can sub-select which sites you would like to see by 
adding them to 'My Favorites'.  Just select the sites you would like to 
add by checking the 'Add' box on the lefthand side and then clicking the 
'Add to Favorites' button at the bottom of the page.</p>

<?php include("links/fav.phtml"); ?>

