<ol>

<li>Open the <a href="<?php echo BASEURL; ?>/cc.phtml" 
target="_new">Current Sortables</a> page.  Click on the <img src="<?php 
echo BASEURL; ?>/images/up-arrow.gif"> underneath the 'Temp' heading to 
sort the temperatures.  Which site has the warmest temperature?  Now click 
on the <img src="<?php echo BASEURL; ?>/images/down-arrow.gif">. Which 
site 
has the coolest temperature?  Given any knowledge you have of today's 
weather, do you know why this difference is occuring?</li>

<li>Find your SchoolNet8 site within the listing of sites on the page.  
How does your site compare to others for variables like temperature and 
wind?  Is your site among the coldest or warmest?</li>

<li>Using the "Favorites" feature of the sortables page, add your 
SchoolNet8 site and a couple of neighboring sites to the list of your 
favorites.  How do the values compare for the sites nearest to you?  If 
there are large differences, can you explain why?</li>

<li>Sort the stations for a variable other than temperature.  How does
your station compare to sites nearest you for this variable?  Is your
site one of the extremes for this variable?</li>

<li>The sortable pages will automatically reload every minute.  Do you 
notice any changes in the data during this time?</li>

</ol>

<h4>Possible Answers</h4>

<p>For all of these questions, it will really depend on the day you view 
the application.  The questions are meant to get you comfortable with 
using the sorting options and favorites feature.</p>
