<?php  /* /index.phtml */
 include("../../config/settings.inc.php");
 $app = "14"; include("../../include/dblog.inc.php"); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style type="text/css" media="screen">@import "../css/main.css";</style>
  <title>SchoolNet8 Viewer</title>
</head>
<body>

<?php include("$nwnpath/include/bar.inc.php"); ?>

<div id="justone">

<h2>KCCI SchoolNet8 Viewer</h2>

<table border=1 width="100%">
<tr>
  <td><a href="#features">Features</a></td>
  <td><a href="#require">Requirements</a></td>
  <td><a href="#download">Download</a></td>
  <td><a href="#support">Support</a></td>
</tr></table>

<p><b>Note for Microsoft Windows Users:</b>  Kenneth Ballard has kindly written a
<a href="http://kcci.kennethballard.com/">Windows viewer application</a> very much
like this one and which does not require Sun Java&trade;.</p>

<div style="float: left;">
<a href="ss/single0.png"><img src="ss/single0_small.png" border=1></a>
<br /><font color="gray">Screenshot of the application</font>
</div>

<ul>
  <li>Ever wanted to monitor your school's weather information from your desktop?</li>
  <li>Ever wanted immediate access to Live KCCI Super Doppler images?</li>
</ul>

<p>With the KCCI SchoolNet8 Viewer, you can do these things and many more!  Best of all, this application is <b>free</b> and runs on any platform that supports <a href="http://java.sun.com" target="_new">Sun Java&trade;</a>. 

<p><b>Note:</b>  This application is provided as-is and without warranty.  This application is intended for educational use only.

<br clear="all">

<p><a name="features"><font size="+1"><b>Features & Screen Shots</b></font></a>
<ul>
<li><a href="ss/single0.png"><i>Single View:</i></a> Updates data for any SchoolNet8 site every minute.</li>
<li><a href="ss/quad0.png"><i>Quad View:</i></a> Shows you current extremes of wind, rain and temperature.</li>
<li><a href="ss/table0.png"><i>Table View:</i></a> Tabular view of all the data in a sortable table.</li>
<li><a href="ss/radar0.png"><i>RADAR View:</i></a> Dynamically update a KCCI Super Doppler view of your choice.</li>
<li><a href="ss/camera0.png"><i>Camera View:</i></a> View from any of the web cameras in the SchoolNet8 Network.</li>
<li>Graphics are delivered in a 640x480 pixel sized window making this perfect for display on a TV system.</li>
<li>The application can dynamically switch between the live data and the RADAR view after an interval of the user's choice.  Again, perfect for an external TV display.</li>
</ul>

<p><a name="require"><font size="+1"><b>System Requirements</b></font></a><br>
An Internet connection is required.
<br>Your system must have Sun Java&trade; version 1.3 or 1.4 installed. Versions prior to 1.3 must have the Swing package addon.  You can download Sun Java&trade; from their <a href="http://java.sun.com/j2se/1.4.1/download.html" target="_new">website</a>.

<p>This application has been successfully tested on RedHat Linux 9, Microsoft Windows 98, 2000 & XP, and Apple Mac OSX 10.2 while running Sun Java&trade; version 1.3.1, 1.4.1 and 1.4.2beta.

<p><a name="download"><font size="+1"><b>Download!</b></font></a><br>
<table width="100%">
<tr><td></td><th align="left">Version:</th><th align="left">Date:</th><th align="left">Download:</th></tr>
<tr><td>Application</td><td>1.5.0</td><td>1 Oct 2006</td><td> <a href="sview.zip">zip file</a> (~1 MB) </td></tr>
<tr><td>Application source code</td><td>1.5.0</td><td>1 Oct 2006</td><td> <a href="sview-src.zip">zip file</a> (~700 KB) </td></tr>
<tr><td>README</td><td></td><td>1 Jan 2004</td><td> <a href="readme.txt">Text</a><br><a href="readme.pdf">PDF</a><br><a href="readme.sxw">OpenOffice.org</a></td></tr>
</table>

<p><a name="support"><font size="+1"><b>Support</b></font></a><br>
This application is provided as-is and without warranty, but we would be happy to help you out with any questions you have. Feel free to email the author of this application, Daryl Herzmann (<a href="mailto:akrherz@iastate.edu">akrherz@iastate.edu</a>).

<p>This application is distributed with full source code under the <a href="http://www.gnu.org/copyleft/gpl.html" target="_new">GNU Public License</a>.

</div> 

<?php include("$nwnpath/include/footer.inc.php"); ?>
