<?php
include("../../config/settings.inc.php");

$app = "18"; include("../../include/dblog.inc.php"); 
include("switcher.php");
$TITLE = "Site Guide";
include("$nwnpath/include/header.inc.php");
$THISPAGE = "training-guide"; include("$nwnpath/include/bar.inc.php"); 

function printModule($module) {
  global $pages;
?>

<h2><?php echo $pages[$module]; ?></h2>

<h4>Objectives:</h4>

<?php include("$module/ob.phtml"); ?>

<h4>SchoolNet8.com Online Resources:</h4>

<?php include("$module/online.phtml"); ?>

<h4>Questions:</h4>

<?php include("$module/qna.phtml"); ?>

<h4>Other Educational Resources:</h4>

<?php include("$module/links.phtml"); ?>

<?php
} 
?>
<div id="guide">


<?php 
$module = isset($_GET["module"]) ? $_GET["module"]: 0;
echo lessonSelect($module); 
?>

<?php if (isset($_GET["module"])) {

  printModule($_GET["module"]);

} else if (isset($_GET['print'])) { 

  reset($pages);
  while( list($key, $val) = each($pages) )
  {
    printModule($key);
  }
} else { ?>
<h3>Welcome to the SchoolNet8.com Website Guide</h3>

<p>Your guide to resources found on this website and links to other useful
information on the Internet.  The guide is presented in 10 lessons designed
to highlight various features of the website:

<ul>
<?php
 reset($pages);
 while (list($key,$val) = each($pages))
 {
   echo "<li><a href=\"index.phtml?module=$key\">$val</a></li>\n";
 }
?>
</ul>

<p>As with the rest of SchoolNet8.com, this guide is a work in progress.
Your comments and feedback are <a href="<?php echo BASEURL; ?>/contact.phtml">certainly welcome</a>.


<?php } ?>

</div>

<?php include("$nwnpath/include/footer.inc.php"); ?>
