<p>The Live Super Doppler8 App is directly linked off the 
homepage, or here:
<div class="urllink">
<img src="<?php echo BASEURL; ?>/images/redhat-web-browser.png">
<h5>Online @ SchoolNet8.com</h5>
<code><a 
href="javascript:new_window_big('<?php echo BASEURL; ?>/GIS/apps/plotter/currents.php?roadcond=show');">Live 
Super Doppler8 App</a></code>
</div>


<p>This application contains a <strong>lot</strong> of features and 
functionality.  The default view looks like this:
<img src="lsdapp/default.png" style="width: 640px;">
<br />Here is a listing of what the various controls do on the side.
<ul>
 <li><b>Map Controls:</b>
  <br />These buttons define map operations.  You need to select one of 
the buttons and then click on the map to either zoom the image in or out, 
recenter the image, zoom it to full extent, or save the map to your 
Desktop.</li>
 <li><b>Time Mode:</b>
  <br />The application can run in either 'Live' mode or 'Archive' mode.  
This allows the ability to look at either current or historical data.  
By clicking on the button, you can select which option you want.</li>

 <li><b>Select Plot Variable:</b>
 <br />You can choose which SchoolNet8 weather variable to plot on the map.</li>

 <li><b>Add + Remove Sites:</b>
  <br />You can dynamically pick which sites are placed on the map.  This 
helps to avoid cluttering the map too much.</li>

 <li><b>Select RADAR:</b>
  <br />You can select to plot either KCCI's Live Super Dopper8 or a 
National Weather Service RADAR.</li>

 <li><b>Show Road Conditions</b>
  <br />Option to show or hide current road conditions.</li>

 <li><b>Show Site Labels</b>
  <br />Option to show or hide SchoolNet8 site labels.  This can help the 
readability of the map.</li>

 <li><b>Generate Map</b>
  <br />Button to have your map redrawn.</li>

 <li><b>Launch Geo-Coder</b>
  <br />This button launches a box allowing you to zoom the map to a 
location of your choice.  You can specify this location by entering a 
Street Address.</li>

 <li><b>I need help!</b>
  <br />Launch a window with help information.</li>
</ol>

<p>Whew!  What an exhaustive list of features.  The point of the 
application is to put as much functionality into one place, so you don't 
have to go to different pages to get different features.</p>
