<ol>

<li>When you first open the Live Super Doppler8 App, you will see the 
statewide road conditions and current RADAR.  Do you notice any 
similiarities between the two data layers?</li>

<li>By default, only data from the KCCI studios SchoolNet8 site is shown.  
Select some more sites underneath the 'Add Sites' heading and then 
'Generate Map'.  Do you notice any differences between the sites?</li>

<li>Select a different plot variable and then click the 'Generate Map' 
button.  Do you still notice differences?  If there is rainfall in the 
area, do you notice differences in 'Today Rainfall' between locations that 
have RADAR activity in the area and those that do not?</li>

<li>Click the button that says "Live/Archive Options".
                A window will open. Click the "Archive Mode" button and
                select May 24, 2004 at 6PM. Describe what you see.</li>

</ol>

<h4>Possible Answers</h4>

<ol>

<li>The answer will depend on the date.  If there is rain or snowfall in 
the area, you should notice some similarities.</li>

<li>Again, will depend on date.</li>

<li>Depends on the date :).</li>

<li>You should notice a bunch of severe warnings.  Do these areas match 
the severe RADAR returns as well?</li>

</ol>
