<ol>

<li>Using the <a href="javascript:new_window_big('<?php echo BASEURL; 
?>/GIS/apps/plotter/currents.php?roadcond=show');">Live Super Doppler8 
App</a>, click the "Live/Archive Options" button, then set the time mode 
to "Archive". Choose the date May 22, 2004 and time 7PM  using the pull 
down menus. Click "Make Changes". Hopefully you will see a map 
valid for that time.  Describe what you see.</li>

<li>Click on the zoom-in button <img src="<?php echo BASEURL; 
?>/images/button_zoomin_off.png">, then click on Boone county, just to the 
northwest of Des Moines. What happens?  Which counties are under Tornado 
Warnings issued by the National Weather Service?  (hint: you may wish to 
zoom in twice to get a better look at the storms.)</li>

<li>Click on the <img src="<?php echo BASEURL; 
?>/images/button_zoomin_off.png"> again, then click on southeastern Boone 
county, which is the "red" county furthest to the east. You'll see a 
closer view of the supercell, or rotating, thunderstorm over southeastern 
Boone county. Hail, which is a very good reflector of radar signals, is 
often shown in purple on Live Super Doppler Radar. Where do you see hail 
in this image? Supercell thunderstorms are often represented by a "hook" 
structure on radar. Where do you see a hook in this image?</li>

<li>Change your plot variable to "Today Rainfall". Then using the 
"control" key, select Ames and Boone. Have these sites received a lot of 
rain so far on this day?  If you were forecasting, do you think those 
locations would pick up more rainfall if the storms to the west came 
directly east?</li>

<li>Assuming the two supercell thunderstorms you see on the screen are 
moving east, which counties MIGHT the National Weather Service issue 
tornado warnings for next?</li>

</ol>

<h4>Possible Answers:</h4>

<ol>

<li>KCCI's Super Doppler is indicating a number of very impressive storms 
just to the north and west of the Des Moines Metro.  The boxes you see on 
the map are the counties that had active weather warnings at the time.  
The red boxes are tornado warnings and yellow boxes are severe 
thunderstorm warnings.</li>

<li>When you click on the zoom button and then the map, your map is 
recentered and zoomed by a factor of 2 to the location you clicked.  
Boone and Carroll County were under Tornado Warnings at this time.</li>

<li><br /><img src="radarapps/boone.png"> You don't need to zoom in far to 
see that this storm in SE Boone County is a nasty one.  The hook echo is 
outlined in white and the possible location of the tornado is given by a 
black dot.</li>

<li>You should get a plot showing Ames with 1.13 inches of rainfall and 
Boone with 1 inch. This was the rainfall for May 22nd up until 7 PM. A 
solid forecast would be for those locations to pick up more rainfall as
the storms to the west are destined to go over the same locations.</li>

<li>If the storms continue to show signs of severe weather, the NWS would 
issue warnings for almost any county east of the thunderstorms once 
the storm threatened the area.</li>

</ol>

