<?php
 include("../../config/settings.inc.php");
 include("../../include/imagemap.inc.php");
 include('../../include/locs.inc.php');
 $app = "09"; include("../../include/dblog.inc.php"); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<HEAD>
<style type="text/css" media="screen">@import "../css/main.css";</style>
  <TITLE>SchoolNet8 | Information</TITLE>
  <META NAME="AUTHOR" CONTENT="Daryl Herzmann">
</HEAD>
<body>

<?php $THISPAGE = "info"; include("$nwnpath/include/bar.inc.php"); ?>

<div id="leftside">

<div class="nb">
<h3>Information</h3>
<div class="nb_content">
<ul>
<li><a href="faq.phtml">Frequently Asked Questions [FAQ]</a></li>
<li><a href="ml.phtml">SchoolNet8 Public E-Mailing Lists</a></li>
<li><a href="webdevel.phtml">Web Developer's Guide</a> to schoolnet8.com</li>
<li><a href="nwsli.phtml">SchoolNet8 Site List</a></li>
</ul>
</div></div>

<div class="nb">
<h3>Information for perspective sites:</h3>
<div class="nb_content">
<!-- http://www.theiowachannel.com/News/575520/index.html -->
<ul>
<li><a href="signup.phtml">SchoolNet8: How To Sign Up</a></li>
</ul>
</div></div>

</div>
<div id="rightside">

<div class="nb">
<h3>Site Calibration:</h3>
<div class="nb_content">
<table><tr>
<td><b>Pressure:</b>
 <ul>
    <li><a href="files/CALIBRATE_PRESSURE.doc">MS DOC</a></li>
    <li><a href="files/CALIBRATE_PRESSURE.htm">HTML</a></li>
    <li><a href="files/CALIBRATE_PRESSURE.pdf">PDF</a></li>
 </ul>
</td>
<td><b>Temperature:</b>
 <ul>
    <li><a href="files/CALIBRATE_TEMP.doc">MS DOC</a></li>
    <li><a href="files/CALIBRATE_TEMP.htm">HTML</a></li>
    <li><a href="files/CALIBRATE_TEMP.pdf">PDF</a></li>
 </ul>
</td>
<td><b>Winds:</b>
 <ul>
    <li><a href="files/CALIBRATE_WIND.doc">MS DOC</a></li>
    <li><a href="files/CALIBRATE_WIND.htm">HTML</a></li>
    <li><a href="files/CALIBRATE_WIND.pdf">PDF</a></li>
 </ul>
</td>
</tr></table>
&nbsp;
</div></div>

<div class="nb">
<h3>Links:</h3>
<div class="nb_content">
<ul>
<li><a href="http://mesonet.agron.iastate.edu" 
   target="_new">Iowa Environmental Mesonet</a></li>
<li><a href="http://www.crh.noaa.gov/dmx/" 
   target="_new">National Weather Service, Des Moines Office</a></li>
<li><a href="http://www.eduplace.com/monthlytheme/march/weather.html"
   target="_new">Education Place Weather Activities</a></li>
<li><a href="http://www.nssl.noaa.gov/edu/"
   target="_new">National Severe Storms Lab Weather Room</a></li>
<li><a href="http://www.usatoday.com/weather/resources/basics/wworks0.htm"
   target="_new">USA Today Atmospheric science resources</a></li>
<li><a href="http://www.meted.ucar.edu/comm_k12.htm"
   target="_new">MetEd resources</a></li>
<li><a href="http://www.space.com/scienceastronomy/101_earth_facts_030722-1.html
">101 Amazing Earth Facts</a></li>
</ul>
</div></div>

</div>
<br clear="all" />

<?php include("$nwnpath/include/footer.inc.php"); ?>
