<?php
 include("../../config/settings.inc.php");
 $app = "09"; include("../../include/dblog.inc.php"); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>SchoolNet8 | Mailing Lists</title>
<style type="text/css" media="screen">@import "../css/main.css";</style>
</head>
<body>

<?php include("$nwnpath/include/bar.inc.php"); ?>

<div id="justone">

 <h3>Mailing Lists</h3>

<p>If you would like to keep up-to-date with current SchoolNet8 news
and application development, feel free to subscribe to either of these
email lists.  Posts are restricted to list members only.</p>

<p><a href="http://mesonet.agron.iastate.edu/mailman/listinfo/kccisnet-announce"
  target="_new">SchoolNet8 Announcements</a>
 <br>Keep up to date with latest SchoolNet8 news and announcements.

<p><a href="http://mesonet.agron.iastate.edu/mailman/listinfo/kccisnet-dev"
  target="_new">SchoolNet8 Development</a>
 <br>List intended for technical discussions and suggestions 
  about the website.  Occasionally, list members will be asked to beta-test
  new features and try out new applications.

</div>

<?php include("$nwnpath/include/footer.inc.php"); ?>
