<?php
 include("../../config/settings.inc.php"); 
 include("$nwnpath/include/sponsors.inc.php");
 include("$nwnpath/include/locs.inc.php");
 $locs = new Locations();

$TITLE = "NWSLI"; include("$nwnpath/include/header.inc.php");
$THISPAGE = "training-web"; include("$nwnpath/include/bar.inc.php");
?>
<div id="justone">
 <h2>SchoolNet8 Sites</h2>

<p>Each SchoolNet8 site is assigned an identifier by the National Weather
Service.  This page lists those identifiers which are used by a number of
applications on this website.</p>

<table>
 <tr><th>NWS ID</th><th>Site Name</th><th>Sponsor</th></tr>

<?php
while ( list($sid, $tbl) = each($locs->table) )
{
  echo '<tr><th>'. $sid .'</th><td>'. $tbl['city'] .'</td><td><a href="'. $baseurl .'tool/clicktru.php?station='. $sid .'">'. $sponsors[$sid]['sponsor'] .'</a></td></tr>';

}
?>

</table>

</div>
<?php include("$nwnpath/include/footer.inc.php"); ?>
