<?php
 include("../../config/settings.inc.php");
 include("../../include/dblog.inc.php"); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style type="text/css" media="screen">@import "../css/main.css";</style>
</head>
<body>


<?php include("$nwnpath/include/bar.inc.php"); ?>
<div id="justone">
 <h2>Information</h2>

<p><b><font color="red">We are currently not accepting SchoolNET applications.
</font><br><br>Please return to this page in the future for updates.</b></p>

</div>
<?php include("$nwnpath/include/footer.inc.php"); ?>
