<?php
 include("../../config/settings.inc.php");
 $app = "09"; include("../../include/dblog.inc.php"); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<HEAD>
  <style type="text/css" media="screen">@import "../css/main.css";</style>
  <TITLE>SchoolNet8 Training</TITLE>
</HEAD>
<body>

<?php $THISPAGE = "training"; include("$nwnpath/include/bar.inc.php"); ?>

<p>This page contains links to various materials available to help with 
the use of this website.

<div id="leftside">

<div class="nb">
<h3>Video Training Materials</h3>
<div class="nb_content">
<ul>
<li><a href="website/">Tour of SchoolNet8 website</a></li>
<li><a href="1minutetrace/">Using 1 minute data graphs</a></li>
<li><a href="snet8viewer">Installation and use of SchoolNet8 Desktop Viewer</a></li>
</ul>
</div></div>


<div class="nb">
<h3>Website Guide</h3>
<div class="nb_content">

Your guide to resources found on this website and links to other useful
information on the Internet.  The guide is presented in 10 lessons designed
to highlight various features of the website:

<p><a href="<?php echo $baseurl; ?>/guide/">View guide</a>

</div></div>

<div class="nb">
<h3>SchoolNet 101</h3>
<div class="nb_content">

<p>SchoolNet 101 is a set of 20 lessons geared toward hands-on science explorati
on and discovery of Meteorological topics.  These topics include weather variables
measured at the SchoolNet8 sites, weather fronts, weather sayings, forecasting,
and much more!

<p><a href="<?php echo $baseurl; ?>/schoolnet101/">View lessons here</a>

</div></div>

</div>
<div id="rightside">

<div class="nb">
<h3>Information</h3>
<div class="nb_content">
<ul>
<li><a href="../info/faq.phtml">Frequently Asked Questions [FAQ]</a></li>
<li><a href="../info/ml.phtml">SchoolNet8 Public E-Mailing Lists</a></li>
<li><a href="../info/webdevel.phtml">Web Developer's Guide</a> to schoolnet8.com</li>
<li><a href="../info/nwsli.phtml">SchoolNet8 Site List</a></li>
</ul>
</div></div>

<div class="nb">
<h3>Site Calibration:</h3>
<div class="nb_content">
<table><tr>
<td><b>Pressure:</b>
 <ul>
    <li><a href="../info/files/CALIBRATE_PRESSURE.doc">MS DOC</a></li>
    <li><a href="../info/files/CALIBRATE_PRESSURE.htm">HTML</a></li>
    <li><a href="../info/files/CALIBRATE_PRESSURE.pdf">PDF</a></li>
 </ul>
</td>
<td><b>Temperature:</b>
 <ul>
    <li><a href="../info/files/CALIBRATE_TEMP.doc">MS DOC</a></li>
    <li><a href="../info/files/CALIBRATE_TEMP.htm">HTML</a></li>
    <li><a href="../info/files/CALIBRATE_TEMP.pdf">PDF</a></li>
 </ul>
</td>
<td><b>Winds:</b>
 <ul>
    <li><a href="../info/files/CALIBRATE_WIND.doc">MS DOC</a></li>
    <li><a href="../info/files/CALIBRATE_WIND.htm">HTML</a></li>
    <li><a href="../info/files/CALIBRATE_WIND.pdf">PDF</a></li>
 </ul>
</td>
</tr></table>
&nbsp;
</div></div>

<div class="nb">
<h3>External Website Links:</h3>
<div class="nb_content">
<ul>
<li><a href="http://mesonet.agron.iastate.edu" 
   target="_new">Iowa Environmental Mesonet</a></li>
<li><a href="http://www.crh.noaa.gov/dmx/" 
   target="_new">National Weather Service, Des Moines Office</a></li>
<li><a href="http://www.eduplace.com/monthlytheme/march/weather.html"
   target="_new">Education Place Weather Activities</a></li>
<li><a href="http://www.nssl.noaa.gov/edu/"
   target="_new">National Severe Storms Lab Weather Room</a></li>
<li><a href="http://www.usatoday.com/weather/resources/basics/wworks0.htm"
   target="_new">USA Today Atmospheric science resources</a></li>
<li><a href="http://www.meted.ucar.edu/comm_k12.htm"
   target="_new">MetEd resources</a></li>
<li><a href="http://www.space.com/scienceastronomy/101_earth_facts_030722-1.html">101 Amazing Earth Facts</a></li>
<li><a href="http://www.josepino.com/other_projects/index?howto_barometer.jpc">How to Make a Barometer</a></li>
<li><a href="http://sunearth.gsfc.nasa.gov/eclipse/eclipse.html">NASA - Past, Present, and Future Eclipses</a></li>
</ul>
</div></div>

</div>
<br clear="all" />

<?php include("$nwnpath/include/footer.inc.php"); ?>
