<?php
include("../../config/settings.inc.php");
include("$nwnpath/include/locs.inc.php");
include("$nwnpath/include/sponsors.inc.php");
include("$nwnpath/include/cameras.inc.php");
$app = "21"; include("$nwnpath/include/dblog.inc.php"); 
$station = isset($_GET["station"]) ? $_GET["station"] : "SAMI4";
$defaultzoom = isset($_GET["station"]) ? 4 : 10;
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
   <style type="text/css" media="screen">@import "../css/main.css";</style>
    <script src="http://maps.google.com/maps?file=api&v=2&key=<?php echo $GMAPS_KEY; ?>" type="text/javascript"></script>
    <script src="GMaps_WMSSpec_0.6.js?v=11" type="text/javascript"></script>
  </head>
  <body>
<?php $THISPAGE="ba"; include("$nwnpath/include/bar.inc.php"); ?>
<div id="justone">
<h2>Google Maps Interface</h2>
    
<div id="map" style="margin-left: 20px; width: 640px; height: 480px"></div>


<p>This page is a test interface using  <a href="http://maps.google.com">Google Maps</a>.  You can click on an icon to get the name of the SchoolNet8 site. The
link presented in the popup window takes you to the site's homepage.</p>
</div>
<?php include("$nwnpath/include/footer.inc.php"); ?>

<script type="text/javascript">
    //<![CDATA[

CustomGetTileUrl=function(a,b,c) {
if (typeof(window['this.myMercZoomLevel'])=="undefined") this.myMercZoomLevel=0; 
if (typeof(window['this.myStyles'])=="undefined") this.myStyles="default"; 
var lULP = new GPoint(a.x*256,(a.y+1)*256);
var lLRP = new GPoint((a.x+1)*256,a.y*256);
var lUL = G_NORMAL_MAP.getProjection().fromPixelToLatLng(lULP,b,c);
var lLR = G_NORMAL_MAP.getProjection().fromPixelToLatLng(lLRP,b,c);
// switch between Mercator and DD if merczoomlevel is set
if (this.myMercZoomLevel!=0 && map.getZoom() < this.myMercZoomLevel) {
    var lBbox=dd2MercMetersLng(lUL.lngDegrees)+","+dd2MercMetersLat(lUL.latDegrees)+","+dd2MercMetersLng(lLR.lngDegrees)+","+dd2MercMetersLat(lLR.latDegrees);
    var lSRS="EPSG:54004";
} else {
    var lBbox=lUL.x+","+lUL.y+","+lLR.x+","+lLR.y;
    var lSRS="EPSG:4326";
}
var lURL=this.myBaseURL;
lURL+="&REQUEST=GetMap";
lURL+="&SERVICE=WMS";
lURL+="&reaspect=false&VERSION=1.1.1";
lURL+="&LAYERS="+this.myLayers;
lURL+="&STYLES="+this.myStyles; lURL+="&FORMAT="+this.myFormat;
lURL+="&BGCOLOR=0xFFFFFF";
lURL+="&TRANSPARENT=TRUE";
lURL+="&SRS="+lSRS;
lURL+="&BBOX="+lBbox;
lURL+="&WIDTH=256";
lURL+="&HEIGHT=256";
lURL+="&GroupName="+this.myLayers;
return lURL;
}



    var map = new GMap2(document.getElementById("map"));
    map.addControl(new GLargeMapControl());
    map.addControl(new GMapTypeControl());

  var tileNEX= new GTileLayer(new GCopyrightCollection(""),1,17);
  tileNEX.myLayers='nexrad-n0r';
  tileNEX.myFormat='image/png';
  tileNEX.myBaseURL='http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r.cgi?';
  tileNEX.getTileUrl=CustomGetTileUrl;

var layer4=[G_SATELLITE_MAP.getTileLayers()[0],G_HYBRID_MAP.getTileLayers()[1],tileNEX];
var custommap4 = new GMapType(layer4, G_SATELLITE_MAP.getProjection(), "Nexrad", G_SATELLITE_MAP);
map.addMapType(custommap4);

    //var wms = new WMSSpec(map.mapTypes[2], "http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r.cgi?", "RADAR", "nexrad-n0r", "", "image/png" );
    //wms.BaseSpecOverride = map.mapTypes[0];
    //wms.reverse = true;
    //map.mapTypes[map.mapTypes.length] = wms; 
    //map.mapTypes.push(wms);

    map.setCenter(new GLatLng(<?php echo $Scities[$station]["lat"]; ?>, <?php echo $Scities[$station]["lon"]; ?>), <?php echo $defaultzoom; ?>);

    function createMarker(point, site_name, site_abrev, lon, lat, sponsor, ui) {
      var marker = new GMarker(point);
      var html = "<div style=\" border: 3px; width: 320px;\"><a href='<?php echo $baseurl; ?>/site.phtml?station="+ site_abrev +"'>" + site_name + "</a></div><br />Sponsored by <a href='<?php echo $baseurl; ?>tool/clicktru.php?station="+ site_abrev +"'>"+ sponsor +"</a><br />"+ ui +"<br /><a href='javascript: map.centerAndZoom(new GPoint("+ lon +", "+ lat +"), 3);'>Zoom To Site!</a><br />&nbsp;";
      GEvent.addListener(marker, "click", function() {
         marker.openInfoWindowHtml(html);
      });
      return marker;
    }

<?php 
while (list($k,$v) = each($Scities)) {
?>
  var point = new GPoint(<?php echo $v["lon"]; ?>, <?php echo $v["lat"]; ?>);
  var marker = createMarker(point, "<?php echo $v["city"] ?>", "<?php echo $k; ?>", <?php echo $v["lon"]; ?>, <?php echo $v["lat"]; ?>, '<?php echo $sponsors[$k]["sponsor"]; ?>','<?php
if (array_key_exists($k, $cameras))
{
        if ($cameras[$k]["active"])
        {
		echo "<img src=\"$baseurl/camera/stills/${k}.jpg\" style=\"width: 320px; height: 240px;\">";
	}
} ?>'
);
  map.addOverlay(marker);
<?php } ?>

    //]]>
    </script>
  </body>
</html>
