<?php
include("../../config/settings.inc.php");
include("$nwnpath/include/locs.inc.php");
$locs = new Locations();
include("$nwnpath/include/sponsors.inc.php");
include("$nwnpath/include/cameras.inc.php");
$app = "21"; include("$nwnpath/include/dblog.inc.php"); 
$station = isset($_GET["station"]) ? $_GET["station"] : "SAMI4";
$defaultzoom = isset($_GET["station"]) ? 10 : 7;
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
   <style type="text/css" media="screen">@import "../css/main.css";</style>
    <script src="http://maps.google.com/maps?file=api&v=2&key=<?php echo $GMAPS_KEY; ?>" type="text/javascript"></script>
  </head>
  <body>
<?php $THISPAGE="mysite-google"; include("$nwnpath/include/bar.inc.php"); ?>
<div id="justone">
<h2>Google Maps Interface</h2>
    
<div id="map" style="border: 1px solid #000; margin-left: 5px; width: 620px; height: 530px"></div>

<p>You can click on an icon to get the name of the SchoolNet8 site. The
link presented in the popup window takes you to the site's homepage. The red
icons have a web camera near to the site.</p>
</div>
<?php include("$nwnpath/include/footer.inc.php"); ?>

<script type="text/javascript">
    //<![CDATA[

 var map = new GMap2(document.getElementById("map"));
 map.addControl(new GLargeMapControl());
 map.addControl(new GMapTypeControl());
 map.addControl(new GOverviewMapControl());

var tileNEX = new GTileLayer(null,null,null); 
tileNEX.getTileUrl = function(tile,zoom) { 
   return "http://mesonet.agron.iastate.edu/cache/tile.py/1.0.0/nexrad-n0r-900913/"+zoom+"/"+tile.x+"/"+tile.y+".png?"+ (new Date()).getTime(); 
};
tileNEX.isPng = function() { return true;};
tileNEX.getOpacity = function() { return 0.5; }


var layer4=[G_NORMAL_MAP.getTileLayers()[0],tileNEX]; 
var custommap4 = new GMapType(layer4, G_SATELLITE_MAP.getProjection(), "Nexrad", G_SATELLITE_MAP);
map.addMapType(custommap4);


map.setCenter(new GLatLng(<?php echo $locs->table[$station]["lat"]; ?>, <?php echo $locs->table[$station]["lon"]; ?>), <?php echo $defaultzoom; ?>);

var icon = new GIcon();
icon.image = "http://labs.google.com/ridefinder/images/mm_20_blue.png";
icon.shadow = "http://labs.google.com/ridefinder/images/mm_20_shadow.png";
icon.iconSize = new GSize(12, 20);
icon.shadowSize = new GSize(22, 20);
icon.iconAnchor = new GPoint(6, 20);
icon.infoWindowAnchor = new GPoint(5, 1);

function tester(nwsli, marker, site_name, sponsor, ui) {
  var tabs = [];
  var html = "<div style=\" border: 3px; width: 320px; height: 290px;\"><a href='<?php echo BASEURL; ?>/site.phtml?station="+ nwsli +"'>" + site_name + "</a><br /><img src=\"<?php echo BASEURL; ?>/gen/kcci.php?station="+nwsli+"\"><br /><!-- Sponsored by <a href='<?php echo BASEURL; ?>/tool/clicktru.php?station="+ nwsli +"'>"+ sponsor +"</a> --><br />&nbsp;</div> ";
  tabs.push( new GInfoWindowTab("Current Ob", html) );
   if (ui.length > 0){
     tabs.push( new GInfoWindowTab("Webcam", ui) );
   }

  marker.openInfoWindowTabsHtml(tabs);
}

function createMarker(point, site_name, site_abrev, lon, lat, sponsor, ui) {

   myicon = new GIcon(icon);
   if (ui.length > 0){
     myicon.image = "http://labs.google.com/ridefinder/images/mm_20_red.png";
   }
   var marker = new GMarker(point, myicon);

   GEvent.addListener(marker, "click", function() {
       tester(site_abrev, marker, site_name, sponsor, ui);
   });
   return marker;
}

<?php 
while (list($k,$v) = each($locs->table)) {
?>
  var point = new GPoint(<?php echo $v["lon"]; ?>, <?php echo $v["lat"]; ?>);
  var marker = createMarker(point, "<?php echo $v["city"] ?>", "<?php echo $k; ?>", <?php echo $v["lon"]; ?>, <?php echo $v["lat"]; ?>, '<?php echo $sponsors[$k]["sponsor"]; ?>','<?php
if (array_key_exists($k, $cameras))
{
        if ($cameras[$k]["active"])
        {
		echo "<img src=\"". BASEURL ."/camera/stills/${k}.jpg\" style=\"width: 320px; height: 240px;\">";
	}
} ?>'
);
  map.addOverlay(marker);

<?php } ?>

/* This causes the map to be redrawn every 5 minutes when viewing NEXRAD */
function myRefreshTileLayer() {
   if (map.getCurrentMapType() == custommap4) {
     map.setMapType(G_NORMAL_MAP);
     map.setMapType(custommap4); 
   }
}
var taskid = setInterval("myRefreshTileLayer()", 300000 ); 

    //]]>
    </script>
  </body>
</html>
