<?php
include("../../config/settings.inc.php");
include("$nwnpath/include/locs.inc.php");
include("$nwnpath/include/sponsors.inc.php");
include("$nwnpath/include/cameras.inc.php");
$app = "21"; include("$nwnpath/include/dblog.inc.php"); 
$station = isset($_GET["station"]) ? $_GET["station"] : "SAMI4";
$defaultzoom = isset($_GET["station"]) ? 10 : 7;
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
   <style type="text/css" media="screen">@import "../css/main.css";</style>
    <script src="http://maps.google.com/maps?file=api&v=2&key=<?php echo $GMAPS_KEY; ?>" type="text/javascript"></script>
  </head>
  <body>
<?php $THISPAGE="ba"; include("$nwnpath/include/bar.inc.php"); ?>
<div id="justone">
<h2>Google Maps Interface</h2>
    
<div id="map" style="border: 1px solid #000; margin-left: 5px; width: 670px; height: 530px"></div>

<p>You can click on an icon to get the name of the SchoolNet8 site. The
link presented in the popup window takes you to the site's homepage. The red
icons have a web camera near to the site.</p>
</div>
<?php include("$nwnpath/include/footer.inc.php"); ?>

<script type="text/javascript">
    //<![CDATA[

CustomGetTileUrl=function(a,b,c) {
if (typeof(window['this.myMercZoomLevel'])=="undefined") this.myMercZoomLevel=0; 
if (typeof(window['this.myStyles'])=="undefined") this.myStyles="default"; 
var lULP = new GPoint(a.x*256,(a.y+1)*256);
var lLRP = new GPoint((a.x+1)*256,a.y*256);
var lUL = G_NORMAL_MAP.getProjection().fromPixelToLatLng(lULP,b,c);
var lLR = G_NORMAL_MAP.getProjection().fromPixelToLatLng(lLRP,b,c);
// switch between Mercator and DD if merczoomlevel is set
if (this.myMercZoomLevel!=0 && map.getZoom() < this.myMercZoomLevel) {
    var lBbox=dd2MercMetersLng(lUL.lngDegrees)+","+dd2MercMetersLat(lUL.latDegrees)+","+dd2MercMetersLng(lLR.lngDegrees)+","+dd2MercMetersLat(lLR.latDegrees);
    var lSRS="EPSG:54004";
} else {
    var lBbox=lUL.x+","+lUL.y+","+lLR.x+","+lLR.y;
    var lSRS="EPSG:4326";
}
var ts = new Date();
var lURL=this.myBaseURL;
lURL+="&REQUEST=GetMap";
lURL+="&SERVICE=WMS";
lURL+="&reaspect=false&VERSION=1.1.1";
lURL+="&LAYERS="+this.myLayers;
lURL+="&STYLES="+this.myStyles; lURL+="&FORMAT="+this.myFormat;
lURL+="&BGCOLOR=0xFFFFFF";
lURL+="&TRANSPARENT=TRUE";
lURL+="&SRS="+lSRS;
lURL+="&BBOX="+lBbox;
lURL+="&WIDTH=256";
lURL+="&HEIGHT=256";
lURL+="&GroupName="+this.myLayers;
lURL+="&bogus="+ ts.getTime() ;
return lURL;
}



    var map = new GMap2(document.getElementById("map"));
    map.addControl(new GLargeMapControl());
    map.addControl(new GMapTypeControl());
    map.addControl(new GOverviewMapControl());

  var tileNEX= new GTileLayer(new GCopyrightCollection(""),1,17);
  tileNEX.myLayers='nexrad-n0r';
  tileNEX.myFormat='image/png';
  tileNEX.myBaseURL='http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r.cgi?';
  tileNEX.getTileUrl=CustomGetTileUrl;

//var layer4=[G_SATELLITE_MAP.getTileLayers()[0],G_HYBRID_MAP.getTileLayers()[1],tileNEX];
var layer4=[G_NORMAL_MAP.getTileLayers()[0],tileNEX]; 
var custommap4 = new GMapType(layer4, G_SATELLITE_MAP.getProjection(), "Nexrad", G_SATELLITE_MAP);
map.addMapType(custommap4);

map.setCenter(new GLatLng(<?php echo $Scities[$station]["lat"]; ?>, <?php echo $Scities[$station]["lon"]; ?>), <?php echo $defaultzoom; ?>);

var icon = new GIcon();
icon.image = "http://labs.google.com/ridefinder/images/mm_20_blue.png";
icon.shadow = "http://labs.google.com/ridefinder/images/mm_20_shadow.png";
icon.iconSize = new GSize(12, 20);
icon.shadowSize = new GSize(22, 20);
icon.iconAnchor = new GPoint(6, 20);
icon.infoWindowAnchor = new GPoint(5, 1);

function tester(nwsli, marker, site_name, sponsor, ui) {
  var tabs = [];
  var html = "<a href='<?php echo $baseurl; ?>/site.phtml?station="+ nwsli +"'>" + site_name + "</a><br /><img height=\"240\" width=\"320\" src=\"<?php echo $baseurl; ?>/gen/kcci.php?station="+nwsli+"\"><br />Sponsored by <a href='<?php echo $baseurl; ?>tool/clicktru.php?station="+ nwsli +"'>"+ sponsor +"</a>";
  tabs.push( new GInfoWindowTab("Current Ob", html) );
   if (ui.length > 0){
     tabs.push( new GInfoWindowTab("Webcam", ui) );
   }

  marker.openInfoWindowTabsHtml(tabs);
}

function createMarker(point, site_name, site_abrev, lon, lat, sponsor, ui) {

   myicon = new GIcon(icon);
   if (ui.length > 0){
     myicon.image = "http://labs.google.com/ridefinder/images/mm_20_red.png";
   }
   var marker = new GMarker(point, myicon);

   GEvent.addListener(marker, "click", function() {
       tester(site_abrev, marker, site_name, sponsor, ui);
   });
   return marker;
}

<?php 
while (list($k,$v) = each($Scities)) {
?>
  var point = new GPoint(<?php echo $v["lon"]; ?>, <?php echo $v["lat"]; ?>);
  var marker = createMarker(point, "<?php echo $v["city"] ?>", "<?php echo $k; ?>", <?php echo $v["lon"]; ?>, <?php echo $v["lat"]; ?>, '<?php echo $sponsors[$k]["sponsor"]; ?>','<?php
if (array_key_exists($k, $cameras))
{
        if ($cameras[$k]["active"])
        {
		echo "<img src=\"$baseurl/camera/stills/${k}.jpg\" style=\"width: 320px; height: 240px;\">";
	}
} ?>'
);
  map.addOverlay(marker);

<?php } ?>

/* This causes the map to be redrawn every 5 minutes when viewing NEXRAD */
function myRefreshTileLayer() {
   if (map.getCurrentMapType() == custommap4) {
     map.setMapType(G_NORMAL_MAP);
     map.setMapType(custommap4); 
   }
}
var taskid = setInterval("myRefreshTileLayer()", 300000 ); 

    //]]>
    </script>
  </body>
</html>
