<?php
 include("../../config/settings.inc.php");
?>
<html>
<body>

<font size="+1"><b>OnAir Control Bar:</b></font>

<p><b>IEM Applications:</b>
<br>
<li><a href="<?php echo BASEURL; ?>/gen/kcci_fe.php?min=1" target="content">Baron Display</a></li>
<li><a href="ccframe.html" target="content">Sortable Currents Table</a></li>
<li><a href="raddisplay.phtml" target="_top">Site RADAR Display</a></li>

<p><b>Other Websites:</b>
<br>
<li><a href="http://pmc.myweather.net/default.asp?host=kcci" target="content">Personal Forecast</a></li>
<li><a href="http://www.theiowachannel.com/" target="content">Iowa Channel .COM</a></li>
<li><a href="<?php echo BASEURL; ?>" target="content">KCCI SchoolNet8</a></li>
<li><a href="http://mesonet.agron.iastate.edu/" target="content">IEM</a></li>

</body>
</html>
