<?php 
include("../../../config/settings.inc.php");
include("$nwnpath/include/cameras.inc.php");
$camid = isset($_GET["camid"]) ? $_GET["camid"] : "KCCI-001";
$app = "30"; include("$nwnpath/include/dblog.inc.php");
$TITLE = "SchoolNet8 | Webcam Lapse Player";
include("$nwnpath/include/header.inc.php"); 
$THISPAGE="webcam-daily"; include("$nwnpath/include/bar.inc.php"); 
?>

<p>The <strong>Web Camera Movie Player</strong> is a Flash application 
that plays recent movies taken from the webcam network.  Please note the 
timestamps to  see when this movie was generated.
<div id="myPlayer"></div>
<form name="theform">
<br /><strong>Select Camera:</strong>
<select name="mycam" onchange="myloader();">
<?php
reset($cameras);
while( list($key, $dict) = each($cameras) )
{
  if ($dict["removed"]){ continue; }
  echo "<option value=\"". $dict["moviebase"] .",$key\">". $dict["name"] ." \n";
}
?>
</select>
<strong>Select Lapse:</strong>
<select name="mylapse" onchange="myloader()">
 <option value="sunrise">Sunrise 
 <option value="morning">Morning (8 AM - 11 AM) 
 <option value="afternoon">Afternoon (1 PM - 4 PM)
 <option value="eve">Sunset 
 <option value="day">Full day
</select>
</form>

<p>Application powered by <a href="http://labs.adobe.com/wiki/index.php/Flash-Ajax_Video_Component">FAVideo</a>

<script src="FAVideo.js" type="text/javascript"></script>
<script src="AC_RunActiveContent.js" type="text/javascript"></script>
<script>
player = new FAVideo("myPlayer");
player.setSize(640,480);
myloader();
player.setAutoPlay(true);

function myloader()
{
  ts = new Date();
  tokens = document.theform.mycam.value.split(",");
  var url = "http://mesonet.agron.iastate.edu/onsite/lapses/auto/"+ tokens[0] +"_"+ document.theform.mylapse.value +".flv?"+ ts.getTime();
  player.load(url);
  player.play();

  document.getElementById("imgbar").innerHTML = "<a href=\"http://localhost/nwnwebsite/tool/clicktru.php?station="+ tokens[1] +"\" target=\"_new\"><img src=\"http://localhost/nwnwebsite/pics/"+ tokens[1] +".gif\" alt=\"Banner\" style=\"border: 0px none ;\"></a>";
}

</script>

<?php include("$nwnpath/include/footer.inc.php"); ?>
