<?php 
include("../../../config/settings.inc.php");
include("$nwnpath/include/cameras.inc.php");
$v = isset($_GET["v"]) ? intval($_GET["v"]) : 0;
$app = "32"; include("$nwnpath/include/dblog.inc.php");
$HEADEXTRA = "
<script src=\"FAVideo.js\" type=\"text/javascript\"></script>
<script src=\"AC_RunActiveContent.js\" type=\"text/javascript\"></script>
";
$TITLE = "SchoolNet8 | Webcam Lapse Learning";
include("$nwnpath/include/header.inc.php"); 
$THISPAGE="webcam-learn"; 
include("$nwnpath/include/bar.inc.php"); 

$appdict = Array(
  0 => Array("ytube" => "", "title" => ""),
  1 => Array("ytube" => "KxOgCFtQFIs",
             "title" => "Horizontally Moving Rainbow"),
  2 => Array("ytube" => "JC85_hyNbkk",
             "title" => "Vertically Moving Rainbow")
);

$yt = $appdict[$v]["ytube"];
$player = "
<div id=\"myPlayer\"></div>
<p><a href=\"http://www.youtube.com/watch?v=${yt}\">YouTube Movie</a><br />
<script>
player = new FAVideo(\"myPlayer\");
player.setSize(640,480);
player.setAutoPlay(true);
player.load(\"http://mesonet.agron.iastate.edu/onsite/lapses/youtube/${yt}.flv\");
player.play();
</script>
";

echo "<div style=\"margin-left: 5px;\">"; 
if ($v == 0){
  include("learn-main.phtml");
} else {
  echo "<a href=\"learn.phtml\">List available modules</a><br />";
  include("ltemplates/${v}.php");
}
echo "</div>";

include("$nwnpath/include/footer.inc.php"); 

?>
