<?php
function listItem($url, $ltext, $name, $selected)
{
  if ($name != $selected)
    return "<li><a href=\"$url\">$ltext</a></li>\n";

  return "<li><a href=\"$url\"><strong style=\"color: #f00;\">$ltext</strong></a></li>\n";
}

?>
<div class="horiz-list" style="border: #bdf solid 2px;">
<ul style="background: #fff; margin: 2px; padding-left: 5px;">
 <li><strong style="color: #bdf;">Webcam Tools:</strong></li>
<?php
  echo listItem($baseurl."/camera/", "Current/Past Images", "current", $THISPAGE);
  echo listItem($baseurl."/camera/bloop.phtml", "Lapse Builder", "lapse", $THISPAGE);
  echo listItem($baseurl."/camera/viewer.phtml", "Live Image", "live", $THISPAGE);
  echo listItem($baseurl."/camera/movies/", "Daily Movies", "daily", $THISPAGE);
  echo listItem($baseurl."/camera/bestof.phtml", "Best Of!", "bestof", $THISPAGE);
?>
</ul>
</div>

