<?php
 include("../../config/settings.inc.php");
 include("../../include/imagemap.inc.php");
 include('../../include/locs.inc.php');
 $app = "31"; include("../../include/dblog.inc.php"); 
 $TITLE = "Best of Webcam Lapses";
 include("$nwnpath/include/header.inc.php");
 $THISPAGE="webcam-bestof"; include("$nwnpath/include/bar.inc.php"); 

?>

<div style="text-align:left; margin: 10px;">
<p>Every day, each online webcamera is capturing five <a href="movies/">time lapses</a>. When one of the lapses is really cool, it is uploaded to YouTube for
easy viewing by others.  You can <a href="http://www.youtube.com/user/akrherz">subscribe</a> to this channel on YouTube and be alerted when new lapses are uploaded.  The interface below shows the most recent 20 cool lapses.</p>

<p>If you are interested in downloading these, please see this <a href="http://mesonet.agron.iastate.edu/onsite/lapses/">directory</a> of movies.  If you
use these lapses, please credit KCCI-TV and Iowa State University.</p>
</div>

<p>
<object width='780' height='445'>
<param name='movie' value='http://www.youtube.com/cp/vjVQa1PpcFNY2yxmlYfUYVBukg_bxvwEgSuchrt7RMs='></param>
<param name='wmode' value='transparent'></param>
<embed src='http://www.youtube.com/cp/vjVQa1PpcFNY2yxmlYfUYVBukg_bxvwEgSuchrt7RMs=' type='application/x-shockwave-flash' wmode='transparent' width='780' height='445'></embed>
</object>


<br clear="all" />

<?php include("$nwnpath/include/footer.inc.php"); ?>
