<?php
 include("../../config/settings.inc.php");
 include("../../include/imagemap.inc.php");
 include('../../include/locs.inc.php');
 $app = "31"; include("../../include/dblog.inc.php"); 
 $TITLE = "SchoolNet8 | Daily Webcam Lapses";
 include("$nwnpath/include/header.inc.php");
 $THISPAGE="webcam-bestof"; include("$nwnpath/include/bar.inc.php"); 


?>

<p>Here are recent SchoolNet8 webcam "best of" time lapses.

<p>
<object width='780' height='445'>
<param name='movie' value='http://www.youtube.com/cp/vjVQa1PpcFNY2yxmlYfUYVBukg_bxvwEgSuchrt7RMs='></param>
<param name='wmode' value='transparent'></param>
<embed src='http://www.youtube.com/cp/vjVQa1PpcFNY2yxmlYfUYVBukg_bxvwEgSuchrt7RMs=' type='application/x-shockwave-flash' wmode='transparent' width='780' height='445'></embed>
</object>


<br clear="all" />

<?php include("$nwnpath/include/footer.inc.php"); ?>
