<?php 
/* Single site webcam image viewer */
include("../../config/settings.inc.php");

/* Log the use of this page */
$app = "25"; include("$nwnpath/include/dblog.inc.php");

/* Include files */
include("$nwnpath/include/cameras.inc.php"); 

/* Lets determine what our default camera ID should be */
$id = isset($_GET["id"]) ? $_GET["id"] : "KCCI-001";
if (isset($_COOKIE['camera']) && ! isset($_GET['id']) )
{
  $id = $_COOKIE['camera']; 
}
$TITLE =  "Live Web Camera Shots";
$HEADEXTRA = "<script language=\"javascript\">

timeID = null;
imgurl = '';
cameraID = '$id';
/* Check to see if we are being called via #KCCI-??? */
var tokens = window.location.href.split('#');
if (tokens.length == 2){
    cameraID = tokens[1];
}
ts = null;
aqlive = false;

/* Stop attempting to refresh the display */
function stop()
{
	clearTimeout(timeID);
}

/* Calls app on the server to get a quasi 'live' image */
function liveShot()
{
	if (aqlive) return;
	aqlive = true;
	stop();
	for (var i=0; i < document.main.id.length; i++)
	{
		if (document.main.id[i].checked)
		{
			cameraID = document.main.id[i].value;
		}
	}
	ts = new Date();
	imgurl = 'live.php?id='+ cameraID +'&'+ ts.getTime();
	document.camera.src = imgurl;
	aqlive = false;
	timeID = setTimeout(\"refreshCamera()\", 300000);
}

function refreshCamera()
{
	stop();
	for (var i=0; i < document.main.id.length; i++)
	{
		if (document.main.id[i].checked)
		{
			cameraID = document.main.id[i].value;
		}
	}
    /* Make the URL Prettier */
    window.location.href = '#'+ cameraID;

    ts = new Date();
    imgurl = 'http://mesonet.agron.iastate.edu/data/camera/640x480/'+ cameraID +'.jpg?'+ ts.getTime();
    document.camera.src = imgurl;

    imgurl = '../images/clogos/'+ cameraID +'_cam.png';
 	document.logo.src = imgurl;

    imgurl = 'http://www.schoolnet8.com/static/radar/'+ cameraID +'/'+ cameraID +'_0.png?'+ ts.getTime();
    document.radar.src = imgurl;

    /* Recall this function in 5 minutes */
    timeID = setTimeout(\"refreshCamera()\", 300000);

    set_cookie(\"camera\", cameraID,2019,1,1);
}
</script>";
$BODYEXTRA = "onload=\"javascript: refreshCamera();\"";
include("$nwnpath/include/header.inc.php");
$THISPAGE = "webcam-live"; include("$nwnpath/include/bar.inc.php"); ?>

<div style="width: 660px;">

<div style="float: left; z-index: 2; border: 10px #000 solid;">
<img name="camera" src="" />
</div>

<div style="float: left; z-index: 3; margin-top: -300px; margin-left: 25px;">
<img name="radar" src="" style="visibility: hidden;" />
</div>

<div style="float: left; z-index: 3; margin-top: -475px; margin-left: 425px;">
<img name="logo" src="" />
</div>

</div>

<br clear="all" />
<form name="main" target="JavaScript: func()">
<div style="float: left; text-align: left; padding-left: 10px;">
<b>Select Camera:</b>
<table width="100%">
<?php
$cnt = 0; 
while (list($cid, $v) = each($cameras) ) {
 if ($v["active"]){
    if ($cnt % 5 == 0){ echo "<tr>"; }
	echo "<td><input type=\"radio\" name=\"id\" value=\"$cid\"  onClick=\"refreshCamera();\">". $v["name"] ."</input></td>\n";
    $cnt += 1;
 }
} 
?>
</table>

<p><b>Overlay RADAR?</b>
<br /><input name="s" type="radio" checked="checked" onclick="document.radar.style.visibility='hidden';">HIDE
<br /><input name="s" type="radio" onclick="document.radar.style.visibility='visible';">SHOW

<p><input type="submit" onclick="liveShot(); return false;" value="Live Shot!"></p>
</div>
</form>

<div style="padding: 5px; float: left; text-align: left;">


<h3>JavaScript Web Camera Viewer Help</h3>

<p>This page should never reload.  The refreshing of the web camera images is controlled by Javascript.  The images will automatically reload:
<ul>
	<li>every 5 minutes</li>
	<li>when you select a camera site</li>
	<li>when you click the 'Live Shot' button.</li>
</ul></p>

<p>The Live Shot images are being acquired directly from the camera!  Please
be patient after clicking the 'Live Shot' button for it may take a few 
seconds to contact the camera.  When the display refreshes 
by itself, the image is coming from a cache which may be up to 5 minutes old.
This is done since bandwidth to the cameras is limited.</p>
</div>

<?php include("$nwnpath/include/footer.inc.php"); ?> 
