<?php include("../../config/settings.inc.php");
    $app = "25"; include("$nwnpath/include/dblog.inc.php");
	include("../../include/cameras.inc.php"); 
	$id = isset($_GET["id"]) ? $_GET["id"] : "KCCI-001";
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-tRansitional.dtd">
<html>
<head>
	<title>SchoolNet8 | Web Cameras</title>
  <style type="text/css" media="screen">@import "../css/main.css";</style>
<script language="javascript">
// <!--

timeID = null;
imgurl = "";
cameraID = "<?php echo $id; ?>";
ts = null;
aqlive = 0;
<?php if (substr($_SERVER["REMOTE_ADDR"],0,7) == "204.227" ) {
	echo "showlogo = 0;";
} else {
	echo "showlogo = 1;";
} ?>
function stop()
{
	clearTimeout(timeID);
}
function liveShot()
{
	if (aqlive) return;
	aqlive = true;
	stop();
 //cameraID = document.main.id[ document.main.id.selectedIndex ].value;
	for (var i=0; i < document.main.id.length; i++)
	{
		if (document.main.id[i].checked)
		{
			cameraID = document.main.id[i].value;
		}
	}
	ts = new Date();
	imgurl = "<?php echo $baseurl; ?>/camera/live.php?id="+ cameraID +"&"+ ts.getTime();
	document.camera.src = imgurl;
	aqlive = false;
	timeID = setTimeout("refreshCamera()", 300000);
}

function refreshCamera()
{
	stop();
 //cameraID = document.main.id[ document.main.id.selectedIndex ].value;
	for (var i=0; i < document.main.id.length; i++)
	{
		if (document.main.id[i].checked)
		{
			cameraID = document.main.id[i].value;
		}
	}
 ts = new Date();
 imgurl = "http://mesonet.agron.iastate.edu/data/camera/640x480/"+ cameraID +".jpg?"+ ts.getTime();
 document.camera.src = imgurl;

 imgurl = "<?php echo $baseurl; ?>/images/clogos/"+ cameraID +"_cam.png";
 if (showlogo) 
 	document.logo.src = imgurl;

 imgurl = "<?php echo $baseurl; ?>/static/radar/"+ cameraID +"/"+ cameraID +"_0.png?"+ ts.getTime();
 document.radar.src = imgurl;
 timeID = setTimeout("refreshCamera()", 300000);
}
function init()
{
	timeID = setTimeout("refreshCamera()", 300000);

}

init();
// -->
</script>
</head>
<body>


<form name="main" target="JavaScript: func()">
<div style="float: left; background-color: #fff; text-align: left; padding: 5px; width: 160px;">
<b>Select Camera:</b>
<?php 
while (list($cid, $v) = each($cameras) ) {
 if ($v["active"]){
	echo "<br /><input type=\"radio\" name=\"id\" value=\"$cid\" ";
	if ($cid == $id) { echo "checked=\"checked\""; }
	echo " onClick=\"refreshCamera();\">". $v["name"] ."\n";
  }
} 
?>

<p><b>Overlay RADAR?</b>
<br /><input name="s" type="radio" checked="checked" onclick="document.radar.style.visibility='hidden';">HIDE
<br /><input name="s" type="radio" onclick="document.radar.style.visibility='visible';">SHOW

<p><input type="submit" onclick="liveShot(); return false;" value="Live Shot!"></p>

</form></div>

<img name="radar" src="<?php echo $baseurl; ?>/static/radar/<?php echo $id; ?>/<?php echo $id; ?>_0.png" style="position: absolute; left: 180px; top: 220px; z-index: 3; visibility: hidden;">
<?php if (substr($_SERVER["REMOTE_ADDR"],0,7) != "204.227" ) { ?>
<img name="logo" src="<?php echo $baseurl; ?>/images/clogos/<?php echo $id; ?>_cam.png" style="position: absolute; left: 580px; top: 35px; z-index: 3;">
<?php } ?>
<img name="camera" src="http://mesonet.agron.iastate.edu/data/camera/640x480/<?php echo $id; ?>.jpg" style="position: absolute; left: 165px; top: 0px; z-index: 2; border: 10px #000 solid;">


<div style="position: absolute; top: 750px; left: 10px; text-align:left; background-color: #fff; padding: 5px;">

<strong>Webcam Tools:</strong> <a href="<?php echo $baseurl; ?>/camera/">Current/Past Images</a> &nbsp; <strong>-</strong> &nbsp; <a href="<?php echo $baseurl; ?>/camera/bloop.phtml">Lapse Builder</a> &nbsp; <strong>-</strong> &nbsp; <a href="<?php echo $baseurl; ?>/camera/viewer.phtml">Live Image</a> &nbsp; <strong>-</strong> &nbsp; <a href="<?php echo $baseurl; ?>/camera/movies/">Daily movies</a>

<p><b>Links:</b> <a href="<?php echo $baseurl; ?>">SchoolNet8.com</a>  |  <a href="<?php echo $baseurl; ?>/camera/">Web Cameras</a>

<h3>JavaScript Web Camera Viewer Help</h3>

<p>This page should never reload.  The refreshing of the web camera images is controlled by Javascript.  The images will automatically reload:
<ul>
	<li>every 5 minutes</li>
	<li>when you select a camera site</li>
	<li>when you click the 'Live Shot' button.</li>
</ul></p>

<p>The Live Shot images are being acquired directly from the camera!  Please
be patient after clicking the 'Live Shot' button for it may take a few 
seconds to contact the camera.  When the display refreshes 
by itself, the image is coming from a cache which may be up to 5 minutes old.
This is done since bandwidth to the cameras is limited.</p>
</div>

</body>
</html>
