<?php include("../../config/settings.inc.php");
 $app = "25"; include("$nwnpath/include/dblog.inc.php");
 include("$nwnpath/include/cameras.inc.php"); 
 $id = isset($_GET["id"]) ? $_GET["id"] : "KCCI-001";
 if (isset($_COOKIE['camera']) && ! isset($_GET['id']) )
 {
   $id = $_COOKIE['camera']; 
 }
 $TITLE =  "Live Web Camera Shots";
 include("$nwnpath/include/header.inc.php");

?>
<script language="javascript">
// <!--

timeID = null;
imgurl = "";
cameraID = "<?php echo $id; ?>";
ts = null;
aqlive = 0;
showlogo = 1;

function stop()
{
	clearTimeout(timeID);
}
function liveShot()
{
	if (aqlive) return;
	aqlive = true;
	stop();
 //cameraID = document.main.id[ document.main.id.selectedIndex ].value;
	for (var i=0; i < document.main.id.length; i++)
	{
		if (document.main.id[i].checked)
		{
			cameraID = document.main.id[i].value;
		}
	}
	ts = new Date();
	imgurl = "<?php echo $baseurl; ?>/camera/live.php?id="+ cameraID +"&"+ ts.getTime();
	document.camera.src = imgurl;
	aqlive = false;
	timeID = setTimeout("refreshCamera()", 300000);
}

function refreshCamera()
{
	stop();
 //cameraID = document.main.id[ document.main.id.selectedIndex ].value;
	for (var i=0; i < document.main.id.length; i++)
	{
		if (document.main.id[i].checked)
		{
			cameraID = document.main.id[i].value;
		}
	}
 ts = new Date();
 imgurl = "http://mesonet.agron.iastate.edu/data/camera/640x480/"+ cameraID +".jpg?"+ ts.getTime();
 document.camera.src = imgurl;

 imgurl = "<?php echo $baseurl; ?>/images/clogos/"+ cameraID +"_cam.png";
 if (showlogo) 
 	document.logo.src = imgurl;

 imgurl = "http://www.schoolnet8.com/static/radar/"+ cameraID +"/"+ cameraID +"_0.png?"+ ts.getTime();
 document.radar.src = imgurl;
 timeID = setTimeout("refreshCamera()", 300000);

  set_cookie("camera", cameraID,2019,1,1);
}
function init()
{
	timeID = setTimeout("refreshCamera()", 300000);

}

init();
// -->
</script>
<?php $THISPAGE = "webcam-live"; include("$nwnpath/include/bar.inc.php"); ?>

<div style="width: 660px;">

<div style="float: left; z-index: 2; border: 10px #000 solid;">
<img name="camera" src="http://mesonet.agron.iastate.edu/data/camera/640x480/<?php echo $id; ?>.jpg" />
</div>

<div style="float: left; z-index: 3; margin-top: -300px; margin-left: 25px;">
<img name="radar" src="http://www.schoolnet8.com/static/radar/<?php echo $id; ?>/<?php echo $id; ?>_0.png" style="visibility: hidden;">
</div>

<div style="float: left; z-index: 3; margin-top: -475px; margin-left: 425px;">
<img name="logo" src="<?php echo $baseurl; ?>/images/clogos/<?php echo $id; ?>_cam.png">
</div>

</div>

<br clear="all" />

<form name="main" target="JavaScript: func()">
<div>
<b>Select Camera:</b>
<table width="100%" style="text-align: left;">
<?php
$cnt = 0; 
while (list($cid, $v) = each($cameras) ) {
 if ($v["active"]){
    if ($cnt % 5 == 0){ echo "<tr>"; }
	echo "<td><input type=\"radio\" name=\"id\" value=\"$cid\" ";
	if ($cid == $id) { echo "checked=\"checked\""; }
	echo " onClick=\"refreshCamera();\">". $v["name"] ."</td>\n";
    $cnt += 1;
 }
} 
?>
</table>

<p><b>Overlay RADAR?</b>
<br /><input name="s" type="radio" checked="checked" onclick="document.radar.style.visibility='hidden';">HIDE
<br /><input name="s" type="radio" onclick="document.radar.style.visibility='visible';">SHOW

<p><input type="submit" onclick="liveShot(); return false;" value="Live Shot!"></p>

</form></div>


<div style="padding: 5px;">


<h3>JavaScript Web Camera Viewer Help</h3>

<p>This page should never reload.  The refreshing of the web camera images is controlled by Javascript.  The images will automatically reload:
<ul>
	<li>every 5 minutes</li>
	<li>when you select a camera site</li>
	<li>when you click the 'Live Shot' button.</li>
</ul></p>

<p>The Live Shot images are being acquired directly from the camera!  Please
be patient after clicking the 'Live Shot' button for it may take a few 
seconds to contact the camera.  When the display refreshes 
by itself, the image is coming from a cache which may be up to 5 minutes old.
This is done since bandwidth to the cameras is limited.</p>
</div>

</body>
</html>
