<?php /* contact.phtml */ 
 include("../config/settings.inc.php");
$TITLE = "Contact";
include("$nwnpath/include/header.inc.php");
include("$nwnpath/include/bar.inc.php"); ?>
<div id="justone">

<h2>Contact Information</h2>

<p>SchoolNet8.com is developed and maintained by Daryl Herzmann of
Iowa State University as a part the <a href="http://mesonet.agron.iastate.edu">Iowa Environmental Mesonet</a> effort.  Feel free to contact him with any
issues you have with the data presented on this site.</p>

<h3>Daryl Herzmann</h3>
<b>Email:</b> akrherz@iastate.edu
<br /><b>Phone:</b> 515.294.5978
<br /><b>Yahoo IM:</b> iowamesonet, <img src="http://opi.yahoo.com/online?u=iowamesonet&m=g&t=1">
</div>

<?php include("$nwnpath/include/footer.inc.php"); ?>
