<?php /* contact.phtml */ 
 include("../config/settings.inc.php");
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>SchoolNet8 | Contact</title>
 <style type="text/css" media="screen">@import "css/main.css";</style>

</head>
<body>
<?php include("$nwnpath/include/bar.inc.php"); ?>

<div id="justone">

<h2>Contact Information</h2>

<p>If you have any questions or comments about this website, please don't 
hesitate to contact Daryl @ Iowa State.</p>

<h3>Daryl Herzmann</h3>
<b>Email:</b> akrherz@iastate.edu
<br /><b>Phone:</b> 515.294.5978
<br /><b>Yahoo IM:</b> iowamesonet, <img src="http://opi.yahoo.com/online?u=iowamesonet&m=g&t=1">
</div>

<?php include("$nwnpath/include/footer.inc.php"); ?>
