<html>
<head>
  <title>KCCI SchoolNet Dev Page</title>
</head>

<frameset rows="125,100%" frameborder="0" framespacing="0" border="0">
  <frame name="top" scrolling="no" marginheight="0" 
    marginwidth="0" target="_top" 
    src="http://www.theiowachannel.com/schoolnet8/detail.html">

  <frameset cols="140,100%" frameborder="0" framespacing="0" border="0">
    <frame name="top" scrolling="no" marginheight="0" 
      marginwidth="0" target="_top" 
      src="http://html.theiowachannel.com/weather/schoolnet8/schoolnet8-sponsors.inc">
    <frame name="content" scrolling="auto" 
      src="index.phtml">
  </frameset>
</frameset></html>		
