<?php
 include("../config/settings.inc.php");
 $app = "16"; include("../include/dblog.inc.php"); 

$TITLE = "Website Features"; include("$nwnpath/include/header.inc.php");
$THISPAGE="training-features"; include("$nwnpath/include/bar.inc.php");
?>
<div id="justone">

<p>With all of the neat features on this website, sometimes it is hard to
find what you are looking for.  This page is meant as guide to the website.

<table class="full">

<?php

function printer($title, $imgurl, $real_link, $show_link, $desc) {

echo '<tr>
  <th bgcolor="#f9ec8e" colspan="2">'. $title .'<br><a href="'. $real_link .'">'. $show_link .'</a></th></tr>
<tr>
  <td><img src="'. $imgurl .'" width="320"></td>
  <td valign="TOP"><b>Description:</b>
  <br />'. $desc .'</td></tr>';
} ?>

<?php 

printer("On Air Graphics",
"gen/kcci.php?station=SAMI4",
"javascript:new_window('". BASEURL ."/gen/kcci_fe.php?station=SAMI4');",
BASEURL ."/gen/kcci_fe.php",
"View a replicated on-air image of data from your favorite SchoolNet8 site
 just like you would see it on KCCI-TV!  The application will automatically
 update at an interval of your choice.");

printer("SchoolNet8 Live Data + Doppler View ",
BASEURL ."/GIS/apps/radar/site.php",
BASEURL ."/site.phtml",
BASEURL ."/site.phtml",
"Zoomed in view of Live KCCI Super Doppler with Live SchoolNet8 data. The
radar image is presented centered on the SchoolNet8 site of your choice 
with neighboring sites also plotted.  You can also pick which variable
you wish plotted on the image.");

printer("Dynamic Super Doppler + SchoolNet8 Plotter",
BASEURL ."/images/dplotter_big.png",
"javascript:new_window_big('". BASEURL ."/GIS/apps/plotter/currents.php');",
BASEURL ."/GIS/apps/plotter/currents.php",
"Dynamically pick the SchoolNet8 sites you wish to plot with the Live
Super Doppler image.  You can also pick which variable to plot.  The image
will dynamically zoom in and out to fit your request.");

printer("Live SchoolNet8 Data",
BASEURL ."/images/currents.png",
BASEURL ."/site.phtml",
BASEURL ."/site.phtml",
"A simple text based listing of the current conditions at a school of your
choice.  You can optionally add another station to the table to give a quick
comparison to another site.");

printer("1 Minute Data Graphs",
BASEURL ."/images/graphing.png",
BASEURL ."/plotting/1trace_fe.phtml",
BASEURL ."/plotting/1trace_fe.phtml",
"This application generates dynamic 1 minute data graphs for the SchoolNet8 
site and date of your choice.  You can view graphs of temperature, dew point,
solar radiation, wind speed, wind direction, pressure and rainfall.");

printer("Historical Data Calendar",
BASEURL ."/images/calendar.png",
BASEURL ."/hist.phtml",
BASEURL ."/hist.phtml",
"This application prints out historical data summaries for a SchoolNet8 site
 of your choice in the format of a calendar. You can view past high and low temperatures, rainfall totals, and wind gust information.");

printer("SchoolNet8 Java Viewer",
BASEURL ."/sview/ss/single0.png",
BASEURL ."/sview/",
BASEURL ."/sview/",
"Monitor your SchoolNet8 site and the entire SchoolNet8 network with this 
handy desktop Java application. This app is handy for those on slow 
Internet connections and still want many of the website functions on
their desktop.");

?>

</table>

<br clear="all" />

</div>
<?php include("$nwnpath/include/footer.inc.php"); ?>
