<?php  /* /index.phtml */
 include("../config/settings.inc.php"); 
 include("$nwnpath/include/locs.inc.php");
 $locs = new Locations();
 include("$nwnpath/include/sponsors.inc.php");
 include("$nwnpath/include/cameras.inc.php");
 include("$nwnpath/include/imagemap.inc.php");
  srand ((float) microtime() * 10000000);
  $station = array_rand($locs->table);
 $app = "05"; include("../include/dblog.inc.php");

$HEADEXTRA = "<script src=\"http://maps.google.com/maps?file=api&v=2&key=$GMAPS_KEY\" type=\"text/javascript\"></script>
<script src='http://www.openlayers.org/api/2.8/OpenLayers.js'></script>
<script src='${baseurl}js/webcams.php'></script>
<script type=\"text/javascript\">
var selectedSite='$station';
var map, jsonlayer;

function updater(){
  var d = new Date();
  cid = eval(\"webcamlookup.\"+ selectedSite );
  document.getElementById(\"lsdimage\").innerHTML = '<a href=\"${baseurl}/site.phtml?station='+ selectedSite +'\"><img src=\"${baseurl}static/radar/'+ selectedSite +'/'+ selectedSite +'_0.png?'+ d.getTime() +'\" border=\"1\" width=\"320\" height=\"240\" alt=\"Live Super Doppler\" style=\"float: right;\"/></a><br />Click on map for more details.';
  document.getElementById('webcamimage').innerHTML = eval(\"webcamsponsor.\"+ cid.replace('-','_') ) +'<a href=\"${baseurl}/camera/viewer.phtml#'+ eval(\"webcamlookup.\"+ selectedSite ) +'\"><img src=\"${baseurl}camera/stills/'+ eval(\"webcamlookup.\"+ selectedSite ) +'.jpg?'+ d.getTime() +'\" border=\"1\" width=\"320\" height=\"240\" alt=\"Webcam\" style=\"float: right;\"/></a><br />Click on image for more details.';

};

function myrefresh(layer){
  if (layer.visibility){
   layer.moveTo(layer.map.getExtent(), true);
  }
}

 function cb_siteOver(feature){
  selectedSite = feature.attributes.sid;
  updater();
 };

 function cb_siteOut(feature){
 };



function olinit(){

  // Build Map Object
  map = new OpenLayers.Map( 'map',{
        projection: new OpenLayers.Projection('EPSG:900913'),
        displayProjection: new OpenLayers.Projection('EPSG:4326'),
        units: 'm',
        wrapDateLine: false,
        numZoomLevels: 18,
        maxResolution: 156543.0339,
        maxExtent: new OpenLayers.Bounds(-20037508, -20037508,
                                         20037508, 20037508.34)
  });

   var styleMap = new OpenLayers.StyleMap({
       'default': {
           fillColor: 'black',
           strokeColor: 'yellow',
           strokeWidth: 2,
           pointRadius: 5,
           strokeOpacity: 1
       },
       'select': {
          fillOpacity: 1,
          strokeColor: 'white',
          fillColor: 'red'
       }
   });


  // Traditional Google Map Layer
  var googleLayer = new OpenLayers.Layer.Google(
                'Google Streets',
                 {'sphericalMercator': true}
            );
  googleLayer.setVisibility(true);

  var superdoppler = new OpenLayers.Layer.WMS.Untiled(\"KCCI Super DopplerHD\",
     \"http://mesonet.agron.iastate.edu/cgi-bin/wms/iowa/kcci.cgi?\",
      {layers:\"kccidoppler\",
       transparent:true,
       format:'image/png'
      }
   );
   superdoppler.setVisibility(true);

   // NEXRAD Composite Layer.
   var nexrad = new OpenLayers.Layer.WMS( 'US NEXRAD',
     'http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r.cgi?', 
     {layers: 'nexrad-n0r', format: 'image/png', transparent: 'true'});
   nexrad.setVisibility(false);


  jsonlayer = new OpenLayers.Layer.GML(\"KCCI SchoolNet8\", 
    \"${baseurl}geojson/kcci.txt?\"+ (new Date()).getTime() ,
            {
                projection: new OpenLayers.Projection('EPSG:4326'),
                format: OpenLayers.Format.GeoJSON, 
                styleMap: styleMap
             });
  jsonlayer.setVisibility(true);
  map.addLayers([googleLayer,superdoppler, nexrad, jsonlayer]);

  selectControl = new OpenLayers.Control.SelectFeature(jsonlayer, {
       onSelect: cb_siteOver, 
       onUnselect: cb_siteOut
   });
   map.addControl(selectControl);
   selectControl.activate();


   var proj = new OpenLayers.Projection('EPSG:4326');
   var proj2 = new OpenLayers.Projection('EPSG:900913');
   var point = new OpenLayers.LonLat(-93.8, 41.8);
   point.transform(proj, proj2);

   map.setCenter(point, 7);
   map.addControl( new OpenLayers.Control.LayerSwitcher({id:'ls'}) );

   window.setInterval(myrefresh, 300876,superdoppler);
   window.setInterval(myrefresh, 301876,nexrad);
   window.setInterval(updater, 60100);

  updater();

}; /* End of olinit() */
</script>
";
$BODYEXTRA = "onload=\"olinit()\"";
$TITLE = "Homepage"; 
include("$nwnpath/include/header.inc.php");
$THISPAGE = "homepage"; include("$nwnpath/include/bar.inc.php"); 
?>

<div style="width:100%; margin-bottom: 5px; margin-left: 10px;">
<b>Welcome</b> to the KCCI SchoolNet8 website<br />sponsored 
by <a href="<?php echo $baseurl; ?>/tool/clicktru.php?station=KCCI">CIPCO</a> and Iowa <a href="http://www.touchstoneenergy.com">Touchstone Energy</a> cooperatives!</p>
</div>


<div id="leftside">

<div class="nb">
<h3>Click on black dot to select a site:</h3>
<div class="nb_content">
<div id="map" style="width:290px; height:380px;"></div>

<p><?php echo kcciSelectAuto($station, "site.phtml?station=", ""); ?></p>
</div></div>


<div class="nb">
<h3>Popular links:</h3>
<div class="nb_content">
<ul>
 <li><a href="javascript:new_window_big('<?php echo $baseurl; ?>GIS/apps/plotter/currents.php');">Live Super Doppler8 App</a></li>
 <li><a href="display.phtml">Loopable Live Super Doppler8</a></li>
 <li><a href="sview/">SchoolNet8 Desktop Java Viewer</a></li>
 <li><a href="camera/bestof.phtml">Best of Webcam Lapes</a></li>
</ul>
</div></div>



</div>
<div id="rightside">


<div class="nb">
<h3>Live Super Doppler8</h3>
<div class="nb_content">
<?php
  /** Begin RANDOM RADAR image */
  $img = sprintf('%sstatic/radar/%s/%s_0.png', $baseurl, $station, $station);
  $camimg = sprintf('%scamera/stills/%s.jpg', $baseurl, $cxref[$station][0]);
  $link = sprintf('%ssite.phtml?station=%s', $baseurl, $station);
  $camlink = sprintf('%scamera/viewer.phtml#%s', $baseurl, $cxref[$station][0]);
  $ct = sprintf('%stool/clicktru.php?station=%s', $baseurl, $station);

  echo "<div id=\"lsdimage\"\"><a href=\"$link\"><img src=\"$img\" border=\"1\" width=\"320\" height=\"240\" alt=\"Live Super Doppler\" style=\"float: right;\"/></a><br />Click on map for more details.</div>";
?>
</div></div>

<div class="nb">
<h3>Nearest SchoolNet8 Webcam</h3>
<div class="nb_content">
<?php
  echo "<div id=\"webcamimage\"><a href=\"$camlink\"><img src=\"$camimg\" border=\"1\" width=\"320\" height=\"240\" alt=\"Webcam\" style=\"float:right;\"/></a><br />Click on image for more details.</div>";
?>
</div></div>


</div>
<br clear="all" />
<div style="text-align:left; margin:5px;">
<p>The KCCI SchoolNet8 is a collection of weather observing stations
located at schools throughout Central Iowa that report 
<b>live</b> information via the Internet.  
While we make every effort to provide reliable and timely data, 
data presented at this website is provided as-is and without warranty.</p>

<p>SchoolNet8 is a contributing data network to the
<a href="http://mesonet.agron.iastate.edu">The Iowa Environmental Mesonet</a> 
of <a href="http://www.iastate.edu">Iowa State University</a>.</p>
</div>
<?php include("$nwnpath/include/footer.inc.php"); ?>
