<?php  /* /index.phtml */
 include("../config/settings.inc.php"); 
 include("$nwnpath/include/locs.inc.php");
 include("$nwnpath/include/sponsors.inc.php");
 include("$nwnpath/include/cameras.inc.php");
 include("$nwnpath/include/imagemap.inc.php");
  srand ((float) microtime() * 10000000);
  $station = array_rand($Scities);
 $app = "05"; include("../include/dblog.inc.php"); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
 <title>SchoolNet8.com</title>
 <style type="text/css" media="screen">@import "css/main.css";</style>

<script language="JavaScript" type="text/javascript">
//<!--
window.name = "basewindow";
function new_window_big(url) {
        link = 
        window.open(url,"Link","toolbar=0,location=0,directories=0,status=0,menubar=no,scrollbars=yes,resizable=yes,width=820,height=620");
} 
function selectWindow() {
 window.open('<?php echo $baseurl; ?>/select.phtml', 'Select', 'toolbar=0,location=0,directories=0,status=0,menubar=no,scrollbars=yes,resizable=yes,width=425,height=700');
}
//END Script-->
</script>
</head>
<body>

<?php $THISPAGE = "homepage"; include("$nwnpath/include/bar.inc.php"); ?>

<p><b>Welcome</b> to the KCCI SchoolNet8 website sponsored 
by <a href="<?php echo $baseurl; ?>/tool/clicktru.php?station=KCCI" target="_new">CIPCO</a> and its member cooperatives!</p>

<div id="leftside">
<h2>Select your site</h2>
<table>
<tr><td><?php echo kcciSelectAuto($station, "site.phtml?station=", "");  ?></td>
<td>or <a href="javascript:selectWindow();">From map</a></td></tr>
</table>
<br />
<h2>Live Super Doppler8</h2>
<?php
  /** Begin RANDOM RADAR image */
  srand((float) microtime() * 10000000);
  $img = sprintf('%s/static/radar/%s/%s_0.png', $baseurl, $station, $station);
  $link = sprintf('%s/site.phtml?station=%s', $baseurl, $station);
  $ct = sprintf('%s/tool/clicktru.php?station=%s', $baseurl, $station);

  echo "<a href=\"$link\"><img src=\"$img\" border=\"1\" width=\"320\" height=\"240\" alt=\"Live Super Doppler\" /></a>
<ul>
 <li><a href=\"$link\">Live Super Doppler8 for your SchoolNet8 Site</a></li>
</ul>";


?>
<h2>What's new for March?</h2>
<a href="images/training_large.jpg"><img src="images/training_small.jpg" style="margin: 5px; float: left;"></a>Thanks to the sponsorship of <a href="tool/clicktru.php?station=KCCI">CIPCO</a> and its member cooperatives, we are pleased to present two SchoolNet8 training workshops this March.  These workshop provide educators with training to put SchoolNet8 to work in their classroom.  Any school participating with SchoolNet8 is free to attend.


</div>
<div id="rightside">

<h2>Popular links:</h2>
<ul>
 <li><a href="javascript:new_window_big('<?php echo $baseurl; ?>GIS/apps/plotter/currents.php');">Live Super Doppler8 App</a></li>
 <li><a href="display.phtml">Loopable Live Super Doppler8</a></li>
 <li><a href="sview/">SchoolNet8 Desktop Java Viewer</a></li>
</ul>


<h2>Web camera sites:</h2>
<?php 
$leftlinks = "";
$rightlinks = "";
$i = 0;
$leftside = ""; $rightside = "";
while (list($id, $v) = each($cameras))
{
	if ($v["active"]) {
	if ($i % 2 == 0) {
	$leftside .= "<li><a href=\"$baseurl/site.phtml?station=$id\">". $v["name"] ."</a></li>";
    } else {
	$rightside .= "<li><a href=\"$baseurl/site.phtml?station=$id\">". $v["name"] ."</a></li>";
    }
	$i += 1; }
} ?>
<table class="side">
<tr><td valign="top"><ul><?php echo $leftside; ?></ul></td><td valign="top"><ul><?php echo $rightside; ?></ul></td></tr>
</table>

<p>The KCCI SchoolNet8 is a collection of weather observing stations
located at schools throughout Central Iowa that report 
<b>live</b> information via the Internet.  
While we make every effort to provide reliable and timely data, 
data presented at this website is provided as-is and without warranty.</p>

<p>SchoolNet8 is a contributing data network to the
<a href="http://mesonet.agron.iastate.edu" target="_new">The Iowa Environmental Mesonet</a> 
of <a href="http://www.iastate.edu" target="_new">Iowa State University</a>.</p>

</div>
<br clear="all" />
<?php include("$nwnpath/include/footer.inc.php"); ?>
