<?php
include("../config/settings.inc.php");
include_once("$nwnpath/include/locs.inc.php");
$locs = new Locations();
include_once("$nwnpath/include/imagemap.inc.php");

$station = isset($_GET['station']) ? substr($_GET['station'],0,5) : 'SKCI4';

if (isset($_COOKIE['station']) && ! isset($_GET['station']) )
{
 $station = $_COOKIE['station'];
}
/* End Session Stuff */


$px = isset($_GET["px"]) ? $_GET['px']: 1;
$size = isset($_GET["size"]) ? $_GET['size'] : "400x400";
list($width, $height) = split("x", $size);
$app = "17"; include("../include/dblog.inc.php"); 

$projInObj = ms_newprojectionobj("init=epsg:4326");
$projOutObj = ms_newprojectionobj("init=epsg:26915");
$point = ms_newpointobj();
$point->setXY($locs->table[$station]["lon"], $locs->table[$station]["lat"]);
$point->project($projInObj, $projOutObj);


$HEADEXTRA = "
<script src='http://www.openlayers.org/api/OpenLayers.js'></script>
<script type=\"text/javascript\">
set_cookie('station', '$station',2019,1,1);
var map;
function olinit(){
    OpenLayers.IMAGE_RELOAD_ATTEMPTS = 2;
            
     mapOptions =  {
        maxExtent: new OpenLayers.Bounds(202271, 4463281, 739205, 4823137 ), 
        projection:'EPSG:26915',
        units:'m'
      };
              
     map = new OpenLayers.Map('map', mapOptions );




  var border = new OpenLayers.Layer.WMS('2007 NAIP',
     'http://ortho.gis.iastate.edu/server.cgi?wmtver=1.0&',
      {layers:'naip_2007',
       projection:'EPSG:26915',
       format:'JPG'
      }
   );
   border.setVisibility(true);

   map.addLayers([border]);
            var markers = new OpenLayers.Layer.Markers( 'Markers' );
            map.addLayer(markers);

   markers.addMarker(
new OpenLayers.Marker(new OpenLayers.LonLat(". $point->x .", ". $point->y .")));


   map.addControl( new OpenLayers.Control.LayerSwitcher({id:'ls'}) );

   var point = new OpenLayers.LonLat(". $point->x .", ". $point->y .");
   map.setCenter(point, 1);



}; /* End olinit() */

</script>";
$BODYEXTRA = "onload=\"olinit()\"";
$TITLE = "SchoolNet8 Ortho Photos";
include("$nwnpath/include/header.inc.php");
$THISPAGE = "mysite-ortho"; 
include("$nwnpath/include/bar.inc.php"); ?>


<h3>Overhead Ortho Photography for <?php echo $locs->table[$station]["city"]; ?></h3>

<div id="map" style="width:100%; height: 360px;"></div>

<p>Switch Site: <?php echo kcciSelectAuto($station, "ortho.phtml?station=", ""); ?>

<div style="text-align: left; padding: 5px;">
<p>2007 Orthophotos. USDA National Agriculture Image Program (NAIP) natural color orthophoto mosaics from aerial photos taken in June - October 2007. The maximum resolution of this imagery is 2 meters. Imagery is provided by the <a href="http://www.gis.iastate.edu">Iowa State University GIS Lab</a>.  The red dot represents where we believe the sensors for
the SchoolNet8 site to be located.  For a majority of the sites, the red dot
was the location of the GPS sensor during the site installation (often in the parking lot).
</div>

<?php include("$nwnpath/include/footer.inc.php"); ?>
