<?php
 /**
  *  sidebar.php
  *     I think that we may build the side bar???
  *  Daryl Herzmann 14 Nov 2002
  */
?>
<html>
<style>.piggy {font-family:arial;font-size:13px;font-weight:bold;}</style>

<style>.piggy {font-family:arial;font-size:13px;font-weight:bold;}</style>
<SCRIPT LANGUAGE="JavaScript1.2" SRC="http://y.ibsys.com/js.ng/section=weather&station=des&subsection=myweather&style=120x90&page.multiads=yes&page.allowcompete=yes&page.uniqueads=yes&Params.styles=1x2_funnel_clear"></SCRIPT>


<!-- Super Doppler! -->
<table align="center" cellpadding="0" cellspacing="0" bgcolor="#6699ff" width="120"><tr><td class="piggy" align="center">Doppler Radar</td></tr></table>
<div align="center"><a href="#" onclick="window.open('http://wx.theiowachannel.com/des/sh/wx/popup_frame.cfm?ImageID=5545', 'Popup640', 'width=640,height=480,scrollbars=0,toolbar=0,status=0,resizable=1'); return false;">
<img src="http://images.ibsys.com/des/images/weather/auto/radar_120x90.gif" width="120" height="90" alt="Doppler Radar" border="0" id="555464"></a></div>



</html>
