<?php
 include("../config/settings.inc.php");
 include("$nwnpath/include/sunrise.inc.php");
/** Get vars */
$var = isset($_GET['var']) ? $_GET['var'] : 'tmpf';
$station = isset($_GET['station']) ? substr($_GET['station'],0,5) : 'SKCI4';

/* Session Stuff 
$expiry = 60*60*24*100; // 100 days
session_start();

if (isset($_SESSION['station']) && ! isset($_GET['station']) )
{
  $station = $_SESSION['station'];
}
$_SESSION['station'] = $station;
*/
if (isset($_COOKIE['station']) && ! isset($_GET['station']) )
{
 $station = $_COOKIE['station'];
}
/* End Session Stuff */

$uri = "site.phtml?station=". $station;
if ($var != "tmpf")
	$uri .= "&amp;var=$var";
if (isset($_GET["add"])) {
	$uri .= "&amp;add=add";
    $station2 = isset($_GET['station2']) ? $_GET['station2']: '';
} else {
   $station2 = '';
}

$s2 = 0;
if ($station2)
{
    $s2 = 1;
	$uri .= "&amp;station2=$station2";
}
 include_once('../include/locs.inc.php');
 include('../include/imagemap.inc.php');
 include('../include/sponsors.inc.php');
 include('../include/currentdb.inc.php');
 include('../include/neighbors.inc.php');
 include('../include/radar_widget.php');
 include('../include/cameras.inc.php');

$containers = Array(
 0 => Array("name"=>"lsd", "display" => "block"),
 1 => Array("name"=>"webcam", "display" => "block"),
 2 => Array("name"=>"current", "display" => "block"),
 3 => Array("name"=>"climo", "display" => "block"),
 4 => Array("name"=>"forecast", "display" => "block"),
 5 => Array("name"=>"links", "display" => "block"),
 6 => Array("name"=>"neighbors", "display" => "block"),
 7 => Array("name"=>"selector", "display" => "block"),
);
$siteconfig = "11111111";
if (isset($_COOKIE['siteconfig'])) $siteconfig = $_COOKIE['siteconfig'];
function str_split_php4($text, $split = 1)
{
    if (!is_string($text)) return false;
    if (!is_numeric($split) && $split < 1) return false;
   
    $len = strlen($text);
   
    $array = array();
   
    $i = 0;
   
    while ($i < $len)
    {
        $key = NULL;
       
        for ($j = 0; $j < $split; $j += 1)
        {
            $key .= $text{$i};
           
            $i += 1;   
        }
       
        $array[] = $key;
    }
   
    return $array;
}

$ar = str_split_php4($siteconfig);
while( list($pos,$val) = each($ar))
{
  if ($val == "0") $containers[$pos]['display'] = "none";

}

 $rW = new radarWidget($station, $var);
 $app = "02"; include("../include/dblog.inc.php"); 
$HEADEXTRA = '
<link rel="stylesheet" type="text/css" href="ext/resources/css/ext-all.css"/>
<script type="text/javascript" src="ext/adapter/ext/ext-base.js"></script>
<script type="text/javascript" src="ext/ext-all.js"></script>
<style>
.x-form-item {margin-left: 6px; border-bottom: 1px solid #ccc;}
.x-panel-header-text { color: #EEEE00; }
.x-panel-header { background: #FFFFFF url(images/sbar.gif) repeat-x scroll left top; }
</style>
<script>
Ext.namespace("nwsli");
nwsli = "'. $station .'";
</script>
<script type="text/javascript" src="js/site.js?v=2"></script>
';
 $TITLE =  $Scities[$station]["city"];
 include("$nwnpath/include/header.inc.php");

?>
<script language="JavaScript" type="text/javascript">
<!--//BEGIN Script
refresh_timeout = setTimeout('document.location=document.location',300000);
set_cookie("station", '<?php echo $station; ?>',2019,1,1);
//END Script-->
</script>
<?php

function sel($svar, $var, $txt){
  echo "<option value='".$var."' ";
  if ($var == $svar) echo "selected=\"selected\"";
  echo ">". $txt ."</option>\n";
}

 $obs = new currentdb();
 $ob1 = $obs->db[$station];
 if (strlen($station2) > 0){
   $s2 =1;
   $ob2 = $obs->db[$station2];
 }

function nbheader($title, $pos, $name)
{
  global $containers, $baseurl;
  $s = "<div class=\"nb\">";
  $s .= "<div class=\"nb_shader\"><a href=\"javascript: reverseLayer('". $name ."',". $pos .");\"><img src=\"${baseurl}/images/shade.gif\" alt=\"shader\"/></a></div>";
  $s .= "<h3>$title</h3>";
  $s .= "<div class=\"nb_content\" id=\"". $name ."\" style=\"display: ". $containers[$pos]['display'] .";\">";
  return $s;
}

?>
<?php $THISPAGE = "mysite-main"; include("$nwnpath/include/bar.inc.php"); ?>

<div id="leftside">
<div id="datagrid"></div>

<p style="margin: 5px;"><?php echo "<b><a href=\"$baseurl/site.phtml?station=$station\">". $Scities[$station]["city"] ."</a></b> SchoolNet8 Site is sponsored by <a href=\"". $baseurl ."tool/clicktru.php?station=$station\">". $sponsors[$station]["sponsor"] ."</a>"; ?>. &nbsp; <a href='javascript:addToFavorites("<?php echo $baseurl . $uri; ?>", "SchoolNet8.com | <?php echo $TITLE; ?>");'>Bookmark this page!</a>
<br />Help report rain and snow in your community by joining <a href="http://iowa.cocorahs.org">CoCoRaHS</a>.</p>

<?php   
if (isset($Scities[$station]["ftm"])) {
 echo "<div style=\"background: #ff0; color: #f00; padding: 2px; border: #000 dashed 1px;\"><b>Special Message</b><br />". $Scities[$station]["ftm"] ."</div>";
} 

?>

<!-- Climate -->
<?php echo nbheader("Climatology for ". date("F d"), 3, "climate"); ?>
<?php
 /* Unserialize climate data! */
 $cfname = sprintf("%s/include/climate_files/2000-%s.txt", $nwnpath, date("m-d") );
 $climate = unserialize( fread(fopen($cfname, 'r'), filesize($cfname) ) );
 $cdict = $climate[ strtolower($Scities[$station]['climate_site']) ];
 $avg_month_precip = $cdict["mtd"];
?>
<table width="100%" cellspacing="0" cellpadding="3">
<thead><tr><th></th><th>Average</th><th>Record</th></tr></thead>
<tr><td>High Temperature</td>
  <td><?php echo sprintf("%.1f", $cdict["high"]); ?></td>
  <td><?php echo sprintf("%s (%s)", $cdict["max_high"], $cdict["max_high_yr"]); ?></td>
</tr>
<tr><td>Low Temperature</td>
  <td><?php echo sprintf("%.1f", $cdict["low"]); ?></td>
  <td><?php echo sprintf("%s (%s)", $cdict["min_low"], $cdict["min_low_yr"]); ?></td>
</tr>
<tr><td>Precipitation:</td>
  <td><?php echo sprintf("%.2f", $cdict["precip"]); ?>"</td>
  <td><?php echo sprintf("%s\" (%s)", $cdict["max_precip"], $cdict["max_precip_yr"]); ?></td>
</tr>
<tr>
 <td colspan="2">Average monthly precip<br /> <?php echo date("M"); ?>-01 to <?php echo date("M-d"); ?></td><td><?php echo sprintf("%.2f", $avg_month_precip ); ?>"</td>
</tr>

<?php 
 $astro = new Astro_Sunrise();
 $astro->setDate(date("Y"), date("m"), date("d"));
 $astro->setCoords( $Scities[$station]['lat'], $Scities[$station]['lon']);
 $astro->setTimezone(date('Z') / 3600 );
 echo sprintf("<tr><td colspan=\"4\">Sunrise: %s AM &nbsp; &nbsp; Sunset: %s PM</td></tr>", $astro->getSunrise(), $astro->getSunset() );
?>
</table>
<br />&nbsp;
</div></div>
</div><!-- End of Leftside -->
<div id="rightside">

<!-- Local Super Doppler8 -->
<?php echo nbheader("Local Super Doppler8:", 0, "lsd"); ?>
<?php $rW->printHTML(); ?>
The lavender sticks are <a href="javascript:help_window('windbarbs');">wind barbs</a>.
</div></div>

<!-- Webcams -->
<?php echo nbheader("Nearest Web Camera:", 1, "webcam"); ?>
<?php
/* webcam section */
$cid = $cxref[$station][0];
/* Age of file on disk, will be good enough! */
if ( filemtime("/home/ldm/data/camera/stills/${cid}.jpg") < (time() - 1200) ){
	echo "<b>Sorry:</b> The ". $cameras[$cid]["name"] ." webcam is currently offline.";
}
else if ($cameras[$cid]["active"])
{
		echo "<ul>
	<li>Build <a href=\"$baseurl/camera/bloop.phtml?station=$cid\">time lapses</a> or view <a href=\"camera/lapses.phtml\">today's movies</a></li>
	<li>View higher resolution <a href=\"$baseurl/camera/viewer.phtml?id=$cid\">640x480 images</a>.</li>
</ul>
<img src=\"$backupbaseurl/camera/stills/${cid}.jpg\" width=\"320\" alt=\"WebCam Still\" height=\"240\" />";
		if ($cameras[$cid]["sponsor"] != "")
		{
			echo "<br />Sponsored by: <a href=\"". $cameras[$cid]["sponsorurl"] ."\">". $cameras[$cid]["sponsor"] ."</a>";
		}
		if ($cameras[$cid]["iservice"] != "" )
		{
			echo "<br />Internet service by: <a href=\"". $cameras[$cid]["iserviceurl"] ."\">". $cameras[$cid]["iservice"] ."</a>";
		}
		if ($cameras[$cid]["hosted"] != "")
		{
            if ($cameras[$cid]["hostedurl"] != "")
			    echo "<br />Hosted by: <a href=\"". $cameras[$cid]["hostedurl"] ."\">". $cameras[$cid]["hosted"] ."</a>";
			else
                echo "<br />Hosted by: <b>". $cameras[$cid]["hosted"] ."</b>";
		}
	} 
else {
	//echo "<b>Sorry:</b> This webcamera is currently offline.";
	}
?>
</div></div>

<!-- Site Resources -->
<?php echo nbheader("Site Resources:", 5, "links"); ?>
<ul>
 <li><a href="<?php echo $baseurl; ?>dl/">Download Data</a></li>
 <li><a href="<?php echo $baseurl; ?>hist.phtml?station=<?php echo $station; ?>">Historical Data Calendar</a></li>
 <li><a href="javascript:new_window_big('<?php echo $baseurl; ?>GIS/apps/plotter/currents.php?st[]=<?php echo $station; ?>');">Live SchoolNet8 &amp; Super Doppler </a></li>
 <li><a href="<?php echo $baseurl; ?>GIS/gm.phtml?station=<?php echo $station; ?>">Google Maps Application</a></li>
 <li><a href="<?php echo $baseurl; ?>ortho.phtml?station=<?php echo $station; ?>">Ortho Photography!</a></li>
 <li><a href="<?php echo $baseurl; ?>plotting/1trace_fe.phtml?station=<?php echo $station; ?>">Plot Data Timeseries</a></li>
 <li><a href="javascript:new_window('<?php echo $baseurl; ?>gen/kcci_fe.php?station=<?php echo $station; ?>');">View On-Air Graphic</a></li>
 <li><a href="http://www.crh.noaa.gov/forecast/MapClick.php?FcstType=text&amp;textField1=<?php echo $Scities[$station]['lat']; ?>&amp;textField2=<?php echo $Scities[$station]['lon']; ?>&amp;site=dmx">National Weather Service 7-Day Forecast</a></li>
</ul>
</div></div>

<!-- Neighbors, no longer used
<?php // echo nbheader("SchoolNet8 Neighbors:", 6, "neighbors"); ?>
</div></div>
-->


<!-- Switcher! -->
<?php echo nbheader("Switch SchoolNet8 Site:", 7, "switch"); ?>
<a href="javascript:selectWindow();">Select from map</a> -or- <b>Select from list</b>

<form method="get" action="site.phtml" name="sitesel2">
<?php
   echo kcciSelect($station);
   /* echo "<br /><input type=\"radio\" value=\"add\" name=\"add\" />Compare Station";
   echo "<input type=\"hidden\" value=\"". $station ."\" name=\"station2\" />";
   echo "<input type=\"hidden\" value=\"". $var ."\" name=\"var\" />"; */
   echo "<input type=\"submit\" value=\"Go!\" /></form>";
?>
<br />Nearest 5 SchoolNet8 Locations:
<ul>
<?php
 for ($i=0;$i<5;$i++){
   $s = sprintf('<li><a href="%ssite.phtml?station=%s">%s</a></li>', 
     $baseurl, $neighbors[$station][$i], $Scities[$neighbors[$station][$i]]['city']);
   echo $s;
 } 
?>
</ul>

</div>
</div>

</div>

<br clear="all" />
<!-- NWS Forecast -->
<?php echo nbheader("National Weather Service Forecast:", 4, "forecast"); ?>
<?php include("/home/ldm/data/kcci/fx/${station}.html"); ?>
</div></div>

<br clear="all" />

<?php include("$nwnpath/include/footer.inc.php"); ?>
