<?php
  // sponsors.php
  //   Library with the sponsor info inside!
  //  Daryl Herzmann 26 Dec 2002

$sponsors = Array(
"SADI4" => Array("name"=> "Adair Casey", "sponsor" => "Guthrie County REC", "url" => "http://www.guthrie-rec.coop"),
"SAEI4" => Array("name"=> "ADM Middle School / Adel", "sponsor" => "CIPCO", "url" => "http://www.cipco.net/"),
"SAFI4" => Array("name"=> "East Union at Afton", "sponsor" => "Southwest Iowa REC", "url" => "http://www.swiarec.com/"),
"SATI4" => Array("name"=> "Anita", "sponsor" => "Farmers Electric Cooperative", "url" => "http://www.farmersrec.com/"),
"SAKI4" => Array("name"=> "Ankeny Christian Academy", "sponsor" => "Consumers Energy", "url" => "http://www.consumersenergy.net/"),
"SBXI4" => Array("name"=> "Baxter", "sponsor" => "Consumers Energy", "url" => "http://www.consumersenergy.net/"),
"SCEI4" => Array("name"=> "Centerville", "sponsor" => "Pella Cooperative Electric ", "url" => "http://www.pella-cea.org/"),
"SALI4" => Array("name"=> "Albia Lincoln Center", "sponsor" => "Touchstone Energy Cooperatives", "url" => "http://www.touchstoneenergy.com/"),
"SPYI4" => Array("name"=> "Perry", "sponsor" => "Touchstone Energy Cooperatives", "url" => "http://www.touchstoneenergy.com/"),
"SAMI4" => Array("name"=> "Ames _ St Cecilia", "sponsor" => "Touchstone Energy Cooperatives", "url" => "http://www.touchstoneenergy.com/"),
"SAUI4" => Array("name"=> "Audubon Community School", "sponsor" => "Touchstone Energy Cooperatives", "url" => "http://www.touchstoneenergy.com/"),
"SBDI4" => Array("name"=> "Bedford", "sponsor" => "Southwest Iowa REC", "url" => "http://www.swiarec.com/"),
"SBKI4" => Array("name"=> "Belmond", "sponsor" => "Prairie Energy Cooperative", "url" => "http://www.prairieenergy.com"),
"SBOI4" => Array("name"=> "United Community / Boone", "sponsor" => "Midland Power Cooperative", "url" => "http://www.midlandpower.com/"),
"SUNI4" => Array("name"=> "BCLUW MS Union", "sponsor" => "Midland Power Cooperative", "url" => "http://www.midlandpower.com/"),
"SBRI4" => Array("name"=> "BGM Elementary / Brooklyn", "sponsor" => "T.I.P. Rural Electric Cooperative", "url" => "http://www.tiprec.com"),
"SBZI4" => Array("name"=> "Blank Park Zoo", "sponsor" => "CIPCO", "url" => "http://www.cipco.net"),
"SCAI4" => Array("name"=> "Kuemper Catholic / Carroll", "sponsor" => "Glidden REC", "url" => "http://www.gliddenrec.com"),
"SCBI4" => Array("name"=> "Coon Rapids - Bayard Jr.-Sr. High School", "sponsor" => "Glidden REC", "url" => "http://www.gliddenrec.com"),
"SCGI4" => Array("name"=> "Clarion", "sponsor" => "Prairie Energy Cooperative", "url" => "http://www.prairieenergy.com"),
"SCHI4" => Array("name"=> "Van Allen Elem. / Chariton", "sponsor" => "Clarke Electric Cooperative, Inc", "url" => "http://www.clarkeelectric.org/"),
"SCNI4" => Array("name"=> "Corning Community / Corning", "sponsor" => "Southwest Iowa REC", "url" => "http://www.swiarec.com/"),
"SCDI4" => Array("name"=> "Wayne Community / Corydon", "sponsor" => "Clarke Electric Cooperative, Inc", "url" => "http://www.clarkeelectric.org/"),
"SCOI4" => Array("name"=> "Colo Elementary / Colo", "sponsor" => "Consumers Energy", "url" => "http://www.consumersenergy.net/"),
"SCSI4" => Array("name"=> "Creston High School / Creston", "sponsor" => "CIPCO", "url" => "http://www.cipco.net/"),
"SDRI4" => Array("name"=> "River Woods / Des Moines", "sponsor" => "CIPCO", "url" => "http://www.cipco.net/"),
"SEGI4" => Array("name"=> "Eagle Grove", "sponsor" => "Prairie Energy Cooperative", "url" => "http://www.prairieenergy.com"),
"SFAI4" => Array("name"=> "Farhamville", "sponsor" => "Calhoun County Electric Cooperative", "url" => "http://www.calhouncountyrec.com/"),
"SFDI4" => Array("name"=> "Fort Dodge", "sponsor" => "Touchstone Energy Cooperatives", "url" => "http://www.touchstoneenergy.com/"),
"SFOI4" => Array("name"=> "Nodaway Valley / Fontanelle", "sponsor" => "Farmers Electric Cooperative", "url" => "http://www.farmersrec.com/"),
"SGLI4" => Array("name"=> "Glidden-Ralston / Glidden", "sponsor" => "Glidden REC", "url" => "http://www.gliddenrec.com"),
"SGRI4" => Array("name"=> "Dallas Center / Grimes", "sponsor" => "CIPCO", "url" => "http://www.cipco.net/"),
"SHUI4" => Array("name"=> "Humboldt", "sponsor" => "Humboldt County REC", "url" => "http://www.humboldtrec.coop/"),
"SIFI4" => Array("name"=> "Rock Run Elementary / Iowa Falls", "sponsor" => "Midland Power Cooperative", "url" => "http://www.midlandpower.com/"),
"SINI4" => Array("name"=> "Emerson Elementary / Indianola", "sponsor" => "Clarke Electric Cooperative, Inc", "url" => "http://www.clarkeelectric.org/"),
"SOGI4" => Array("name"=> "Ogden", "sponsor" => "Midland Power Cooperative", "url" => "http://www.midlandpower.com/"),
"SJEI4" => Array("name"=> "Jefferson Scranton H.S.", "sponsor" => "Midland Power Cooperative", "url" => "http://www.midlandpower.com/"),
"SJWI4" => Array("name"=> "Jewell", "sponsor" => "Midland Power Cooperative", "url" => "http://www.midlandpower.com/"),
"SJCI4" => Array("name"=> "Jordan Creek WDM", "sponsor" => "CIPCO", "url" => "http://www.cipco.net/"),
"SKCI4" => Array("name"=> "KCCI Studios in Des Moines", "sponsor" => "CIPCO", "url" => "http://www.cipco.net/"),
"S03I4" => Array("name"=> "Iowa State Fair", "sponsor" => "Dynamic Broadband", "url" => "http://www.dybb.com/"),
"SKNI4" => Array("name"=> "West Elementary / Knoxville", "sponsor" => "Pella Cooperative Electric ", "url" => "http://www.pella-cea.org/"),
"SOCI4" => Array("name"=> "Oskaloosa", "sponsor" => "Pella Cooperative Electric ", "url" => "http://www.pella-cea.org/"),
"SLEI4" => Array("name"=> "Leon ", "sponsor" => "Clarke Electric Cooperative, Inc", "url" => "http://www.clarkeelectric.org/"),
"SLMI4" => Array("name"=> "Latimer", "sponsor" => "Franklin REC", "url" => "http://www.franklinrec.com/"),
"SLUI4" => Array("name"=> "LuVerne", "sponsor" => "Touchstone Energy Cooperatives", "url" => "http://www.touchstoneenergy.com/"),
"SLOI4" => Array("name"=> "Lamoni Community School", "sponsor" => "Southwest Iowa REC", "url" => "http://www.swiarec.com/"),
"SMAI4" => Array("name"=> "Fisher Elementary / Marshalltown", "sponsor" => "Consumers Energy", "url" => "http://www.consumersenergy.net/"),
"SMDI4" => Array("name"=> "Madrid", "sponsor" => "Midland Power Cooperative", "url" => "http://www.midlandpower.com/"),
"SMLI4" => Array("name"=> "Mallard", "sponsor" => "Humboldt County REC", "url" => "http://www.humboldtrec.coop/"),
"SMNI4" => Array("name"=> "Montezuma Community School", "sponsor" => "Touchstone Energy Cooperatives", "url" => "http://www.touchstoneenergy.com/"),
"SMSI4" => Array("name"=> "NW Webster", "sponsor" => "Touchstone Energy Cooperatives", "url" => "http://www.touchstoneenergy.com/"),
"SMOI4" => Array("name"=> "Mount Ary Community School", "sponsor" => "Southwest Iowa REC", "url" => "http://www.swiarec.com/"),
"SMUI4" => Array("name"=> "Murray", "sponsor" => "Clarke Electric Cooperative, Inc", "url" => "http://www.clarkeelectric.org/"),
"SNEI4" => Array("name"=> "Berg M.S. / Newton ", "sponsor" => "Consumers Energy", "url" => "http://www.consumersenergy.net/"),
"SNVI4" => Array("name"=> "Nevada", "sponsor" => "Consumers Energy", "url" => "http://www.consumersenergy.net/"),
"SOSI4" => Array("name"=> "Clarke Community / Osceola", "sponsor" => "Clarke Electric Cooperative, Inc", "url" => "http://www.clarkeelectric.org/"),
"SPAI4" => Array("name"=> "Panorama / Panora", "sponsor" => "Guthrie County REC", "url" => "http://www.guthrie-rec.coop"),
"SPEI4" => Array("name"=> "Pella M.S.", "sponsor" => "Pella Cooperative Electric ", "url" => "http://www.pella-cea.org/"),
"SPKI4" => Array("name"=> "Polk City", "sponsor" => "CIPCO Cooperative", "url" => "http://www.cipco.org/"),
"SROI4" => Array("name"=> "Rockwell City", "sponsor" => "Calhoun County Electric Cooperative", "url" => "http://www.calhouncountyrec.com/"),
"SSTI4" => Array("name"=> "Stuart", "sponsor" => "CIPCO", "url" => "http://www.cipco.net/"),
"SSUI4" => Array("name"=> "Sully Christian", "sponsor" => "Pella Cooperative Electric ", "url" => "http://www.pella-cea.org/"),
"SWAI4" => Array("name"=> "Wall Lake", "sponsor" => "Sac County REC", "url" => "http://www.sacrec.coop/"),
"SWBI4" => Array("name"=> "Webster City", "sponsor" => "Prairie Energy Cooperative", "url" => "http://www.prairieenergy.com"),
"SWII4" => Array("name"=> "Winterset Community", "sponsor" => "Farmers Electric Cooperative", "url" => "http://www.farmersrec.com/"),
"KCCI" => Array("name"=> "KCCI", "sponsor" => "CIPCO Cooperative", "url" => "http://www.cipco.org/"),
"SIAI4" => Array("name"=> "Iowa Christian Academy", "sponsor" => "CIPCO Cooperative", "url" => "http://www.cipco.org/"),
"SBMI4" => Array("name"=> "Bloomfield", "sponsor" => "Southern Iowa Electric Cooperative, Inc", "url" => "http://southerniowarec.coop/"),
"SAGI4" => Array("name"=> "Algona", "sponsor" => "Humboldt County REC", "url" => "http://www.humboldtrec.coop/"),
"STQI4" => Array("name"=> "Meskwaki Settlement School Tama", "sponsor" => "T.I.P. Rural Electric Cooperative", "url" => "http://www.tiprec.com"),
"CIPCO" => Array("name"=> "KCCI", "sponsor" => "CIPCO Cooperative", "url" => "http://www.cipco.org/"),
"TOUCH" => Array("name"=> "KCCI", "sponsor" => "Touchtone Cooperative", "url" => "https://touchstoneenergy.cooperative.com/public/index.html"),
);
?>
