<p>The goal of this lesson is to show how to use the Orthophotography that 
is available on the website.  Orthophotos are simply images that have been 
processed to remove any disortion caused by terrain effects in 
relationship to the camera.  Think about taking a picture of the mountains 
from an airplane.  The differing heights of the mountains will cast 
shadows on your image.  Orthophotography tries to remove these 
distortions. You have probably seen these images used on National TV 
during Iraq coverage to show areas of the country from above.</p>

