<ol>

<li>Asphalt and concrete readily absorb the sun's energy during the day 
and release it as heat during the afternoon and evening. Take a look at a 
shot of the SchoolNet8 site at <a href="<?php echo $baseurl; 
?>/ortho.phtml?station=SAKI4">Ankeny Christian Academy</a>. How might the 
school's surroundings affect the temperatures recorded there?</li>

<li>The northern half of Iowa was scoured nearly flat by glaciers during 
the last ice age. As a result, the topography there offers little to 
resist the often windy conditions that affect the northern plains. Look at 
5-meter-resolution pictures of the Schoolnet sites in Farnhamville and 
Boone. How might the land surrounding the sites affect the winds measured 
there?</li>

<li>Hills, buildings, and trees surrounding a SchoolNet8 site might make 
the wind speeds and gusts recorded by a site seem less than they actually 
are for the surrounding area. The scientific term for this would be that 
the site is not representative of the greater area. Look at a 1-meter 
resolution picture of our site at <a href="<?php echo $baseurl; 
?>/ortho.phtml?station=SOCI4">Oskaloosa Christian school</a>. How might 
the site's surroundings affect the winds recorded there?</li>

<li>Crops such as corn and beans release a great deal of moisture into the 
air during the growing season through a process called evapotranspiration. 
This can create unrepresentatively high dewpoint and humidity readings to 
be recorded by a weather station. Take a look at 2-meter resolution ortho 
photography of our site at <a href="<?php echo $baseurl;
?>/ortho.phtml?station=SROI4">Rockwell City</a>. How 
might the readings at the 
school on a summer day with southerly winds be affected by its 
surroundings?</li>

</ol>

<h4>Possible Answers:</h4>

<ol>

<li>Urban areas absorb and retain a greater amount of the solar radiation 
received than rural areas do.  This phenomena is referred to as an urban 
heat island.  The effects are increased temperatures during the day and 
night, particularly on sunny days.  The effect is more pronounced for 
the larger cities than small towns.  Cities like Des Moines 
function as urban heat islands quite often.</li>

<li>In general, wind will flow faster when faced with fewer obstacles.  
So in the rural and flat areas of Iowa, the winds would be able to blow 
faster 
than in urban and forest areas.</li>

<li>There are numerous trees in the area which would tend to resist the 
wind flow and cause the SchoolNet8 site to record weaker winds than 
what are prehaps observed outside of town.</li>

<li>The large field just to the south of the SchoolNet8 site will 
increase humidities during the growing season due to 
evapotranspiration.  The fields on the other sites of the school will 
probably affect humidities as well.</li>

</ol>
