<p>The SchoolNet8.com webcamera resources can be found here:

<?php include("links/webcam.phtml"); ?>

<p>By default, this page contains an overview of the most recent images 
grabbed from the network of webcams. These images are updated every 5 
minutes during normal weather and every minute during severe weather.  
Besides viewing the most recent image, you can do a whole lot more with 
the cameras.  The page also contains a form which allows you to choose the 
time of the webcamera image.  You need to choose the 'Archived Images' 
option and then set the form to the date and time of your choice.  Note 
that not every site goes back to the beginning of the archive.

<p>There are also two links on the page to special webcam applications.  
One takes you to an application that displays loops of historical 
webcam images.  You can find this application here:

<?php include("links/webcamloop.phtml"); ?>

<p>There is also an application to view high resolution and live images 
from the cameras.  You can find the page here:

<?php include("links/webcamlive.phtml"); ?>

