<ol>

<li>Take a look at the current images from the network of cameras.  Can 
you see any differences between the sites?  Are some sites cloudier than 
others?  Do some sites have snow on the ground?</li>

<li>Take a look at a webcamera loop using the webcam historical loops 
page.  Do you notice anything changing during the loop?  Can 
you see rain falling or snow melting?</li>

<li>The Iowa Environmental Mesonet maintains a page filled with 
interesting lapses from the webcamera network.  You can access it <a 
href="http://mesonet.agron.iastate.edu/cool/" target="_new">here</a>.  
You can download any of the movies on that page.  The format is simple 
MPEG1, so hopefully it plays on your computer.  Describe what you see in 
those movies.  Have you ever seen anything similar in real life?</li>

<li>The tornado video from the previous question's site is extremely 
interesting.  Did you notice how the tornado first appears near the ground 
and then the funnel descends to the circulation?  How might you think 
meteorologists would use the webcameras during servere weather?  What do 
the cameras provide that the SchoolNet8 weather sites do not?</li>

</ol>

<h4>Possible Answers:</h4>

<ol>

<li>Depending on the day, you may or may not see differences in the 
images.  If you do see differences, look for differences in weather 
variables like air temperature.  Perhaps the differences in the weather 
varaibles, for example, temperature, can be explained by what you see from 
the webcams.</li>

<li>Again, this will depend on the day.</li>

<li>Most of those movies depict severe weather or pretty cloud formations.  
The Humboldt movie of vigorous convection has been used in a number of 
classrooms to illustrate explosive convection.  Explosive convection is 
rapidly rising 'bubbles' of air in a thunderstorm.  Seeing such impressive 
development is a sign of a storm with lots of energy associated with it 
and a chance to produce wind, hail, and/or tornados.</li>

<li>TV and National Weather Service meteorologists absolutely love the 
webcameras.  They provide that eye in the sky that automated weather 
sensors can not provide.  They can visually show the clouds and what 
is happening on the ground whereas automated weather sensors can 
not.</li>

</ol>
