<?php
  /** 1trace_fe.phtml
   */

include("../../config/settings.inc.php");
$app = "03"; include("../../include/dblog.inc.php");
$station = isset($_GET['station']) ? $_GET["station"] : "";
$nwsli = $station;
include("../../include/imagemap.inc.php");
include("../../include/forms.inc.php");

include("../../include/select_widget.php");
$sw = new selectWidget($nwnpath, "bogus");
$sw->performQuery($_GET);
if (strlen($sw->selectedSite) > 0)
{
  $station = $sw->selectedSite;
}
else 
{
 $sw->setShowCamera(false);
 $sw->setShowRADAR(false);
 $sw->drawMap();
}

/** Vars */
$year = isset($_GET['year']) ? $_GET["year"]: date("Y");
$month = isset($_GET['month']) ? $_GET["month"]: date("m");
$day = isset($_GET['day']) ? $_GET["day"]: date("d");


$TITLE = "One Minute Time Series";
$THISPAGE = "mysite-trace"; 
include("$nwnpath/include/header.inc.php");
include("$nwnpath/include/bar.inc.php"); ?>

<p>This application generates charts showing various variables throughout a date of your choice. Note that the archive begins 12 Feb 2002.</p>

  <form method="GET" action="1trace_fe.phtml" name="select">
  <?php

    if (strlen($month) == 0 ){
	$month = date("m");
    }
    if (strlen($day) == 0 ){
        $day = date("d");
    }
    if (strlen($year) == 0 ){
        $year = date("Y");
    }
?>

<table border=1 cellspacing=0 cellpadding=2 align="center">
<tr>
	<th>Select Site or <a href="1trace_fe.phtml">Show Map</a></th>
	<th colspan=3>Select The Date:</th>
	<td rowspan=2><input type="submit" value="Make Plot"></td></tr>

<tr>
	<td><?php echo kcciSelect($station); ?></td>
	<td><?php echo yearSelect(2002, $year, "year"); ?></td>
	<td><?php echo monthSelect($month, "month"); ?></td>
	<td><?php echo daySelect($day, "month"); ?></td></tr>
</table>

<?php
if (strlen($station) > 0 ) {

?>

<p>
 <?php 
echo sprintf("<p><img src=\"http://mesonet.agron.iastate.edu/plotting/snet/1min_T.php?station=%s&year=%s&month=%s&day=%s\" />", $station, $year, $month, $day);
echo sprintf("<p><img src=\"http://mesonet.agron.iastate.edu/plotting/snet/1min_V.php?station=%s&year=%s&month=%s&day=%s\" />", $station, $year, $month, $day);
echo sprintf("<p><img src=\"http://mesonet.agron.iastate.edu/plotting/snet/1min_P.php?station=%s&year=%s&month=%s&day=%s\" />", $station, $year, $month, $day);
?>


<p><b>Note:</b> The wind speeds are indicated every minute by the red line. 
The blue dots represent wind direction and are shown every 10 minutes.</p>


<?php
} else {
?>

<p>or select from this map...

<div align="center">
<input type="image" name="map" src="<?php echo $sw->imgurl; ?>">
</div>

<?php }  ?>

</form>


<?php include("$nwnpath/include/footer.inc.php");
