
<ul>
 <li><a href="<?php echo BASEURL; ?>">SchoolNet8.com Homepage</a></li>
 <ul>
  <li><a href="javascript:new_window_big('<?php echo BASEURL; ?>/GIS/apps/plotter/currents.php?roadcond=show');">1. Live Super Doppler8 App</a></li>
  <li><a href="javascript:selectWindow();">2. SchoolNet8 Site Selector</a></li>
  <li><a href="<?php echo BASEURL; ?>/sview/">3. SchoolNet8 Desktop Java Viewer</a></li>
  <li><a href="<?php echo BASEURL; ?>/current.phtml">4. Current Conditions</a></li>
  <ul>
    <li><a href="<?php echo BASEURL; ?>/cc.phtml">40. Current Sortables</a></li>
    <li><a href="<?php echo BASEURL; ?>/wap/index.phtml">41. Obs for Wireless Users</a></li>
    <li><a href="<?php echo BASEURL; ?>/tool/walerts.phtml">42. Wind Gust Alerts</a></li>
    <li><a href="http://mesonet.agron.iastate.edu/cgi-bin/precip/catSNET.py">43. Historical SchoolNet Rainfall</a></li>
    <li><a href="http://mesonet.agron.iastate.edu/GIS/data/datasets/snet_current.zip">44. GIS Shapefile of current obs</a></li>
  </ul>
  <li><a href="<?php echo BASEURL; ?>/dl/">5. Download</a></li>
  <ul>
    <li><a href="<?php echo BASEURL; ?>/dl/index.phtml">50. Download Obs</a></li>
    <li><a href="<?php echo BASEURL; ?>/dl/index.phtml?page=sum">51. Download Summary Data</a></li>
    <li><a href="<?php echo BASEURL; ?>/dl/history.phtml">52. Observational Record</a></li>
    <li><a href="<?php echo BASEURL; ?>/dl/params.phtml">53. Data Parameters</a></li>
  </ul>
  <li><a href="<?php echo BASEURL; ?>/info/">6. Information</a></li>
  <ul>
    <li><a href="<?php echo BASEURL; ?>/info/faq.phtml">60. FAQ</a></li>
    <li><a href="<?php echo BASEURL; ?>/info/ml.phtml">61. Public Email Lists</a></li>
    <li><a href="<?php echo BASEURL; ?>/info/signup.phtml">62. Sign up for SchoolNet8</a></li>
    <li><a href="<?php echo BASEURL; ?>/info/files/CALIBRATE_PRESSURE.htm">63. Calibrate Pressure</a></li>
    <li><a href="<?php echo BASEURL; ?>/info/files/CALIBRATE_TEMP.htm">64. Calibrate Temperature</a></li>
     <li><a href="<?php echo BASEURL; ?>/info/files/CALIBRATE_WIND.htm">65. Calibrate Winds</a></li>
  </ul>
  <li><a href="<?php echo BASEURL; ?>/guide/">7. SchoolNet8 Website Guide</a></li>
  <li><a href="<?php echo BASEURL; ?>/camera/">8. Webcams</a></li>
  <ul>
    <li><a href="<?php echo BASEURL; ?>/camera/bloop.phtml">80. Dynamic Loops</a></li>
    <li><a href="<?php echo BASEURL; ?>/camera/viewer.phtml">81.  HiRes and Live WebCam Images</a></li>
    <li><a href="<?php echo BASEURL; ?>/camera/lapses.phtml">82.  Daily webcamera lapses</a></li>
  </ul>
   <li><a href="<?php echo BASEURL; ?>//site.phtml">9. My Site Current Conditions</a></li>
   <ul>
     <li><a href="<?php echo BASEURL; ?>//ortho.phtml">90. Ortho Photography</a></li>
     <li><a href="<?php echo BASEURL; ?>/plotting/1trace_fe.phtml">91. 1 minute data timeseries</a></li>
     <li><a href="javascript:new_window('<?php echo BASEURL; ?>/gen/kcci_fe.php');">92. On Air Graphic</a></li>
   </ul>
 </ul>
</ul>
