<ol>
  <li>Which Schoolnet8.com application would provide a quick way to find a 
site's high and low temperature for July 4th 2004?</li>

  <li>Which SchoolNet8.com application would provide a good way to look at 
live county-level radar and live SchoolNet8 data?</li>

  <li>Where can you go to generate maps of RADAR, observations, and 
NWS warnings for an area and time of your choice?</li>

  <li>Which application allows you to plot a graph of a SchoolNet8 site's 
weather values for a particular date?</li>

</ol>

<h4>Possible Answers:</h4>

<ol>

<li>The <a href="<?php echo $baseurl; ?>/hist.phtml">Historical Data 
Calendar</a> allows you to view a monthly calendar of daily high and low 
temperatures with peak wind gusts and daily rainfall. </li>

<li>On the <a href="<?php echo $baseurl; ?>/site.phtml">My Site Current 
Conditions</a> page a county scale RADAR image for your site is 
immediately available.  You can loop this image by selecting the 
'Loop' link just above the map.</li>

<li>The <a 
href="javascript:new_window_big('<?php 
echo $baseurl; ?>/GIS/apps/plotter/currents.php?roadcond=show');">Live 
Super Doppler8 App</a> gives you a completely customizable look at 
current or historical weather.  You can select the time and area of 
your choice.</li>

<li>The <a 
href="<?php echo $baseurl; ?>/plotting/1trace_fe.phtml">1 minute data 
timeseries</a> plots daily graphs of weather for a site and 
date of your choice.</li>

</ol>
