<p>The SchoolNet8.com website has numerous ways that you can view solar 
radiation data.  You can view the current value of solar radition 
expressed in watts per meter squared from your site here:

<?php include("links/mysite.phtml"); ?>

<p>Another interesting way to look at solar radiation data is to view a 
graph of how it changes throughout the day.  You can view these graphs 
here:

<?php include("links/oneminute.phtml"); ?>


