<ol>

<li><br /><a href="<?php echo BASEURL; 
?>/plotting/1trace_fe.phtml?station=SCSI4&year=2004&month=6&day=30"><img 
src="solar/68_2004_06_30_1.png" border="0"></a>
 <br />Describe the solar radiation trend (black line) for this day. Some 
might describe the shape of the curve as a large bell, like the liberty 
bell in Philadelphia.  What causes this bell shaped curve?  Can you 
explain the small variations in the curve during the afternoon?  What 
events are shown on this graph at roughly 6 AM and 9 PM?</li>

<li><br /><a 
href=<?php echo BASEURL; ?>/plotting/1trace_fe.phtml?station=SINI4&year=2004&month=5&day=17"><img 
src="solar/38_2004_05_17_1.png" border="0"></a>
 <br />In the first example, the solar radiation curve was relatively 
smooth.  In this example, the curve is very rough and contains 
alternating high 
and low values.  Can you explain why?  Also notice the temperature 
values during the afternoon.  Can you explain why the temperature 
dropped a few degrees around 2 PM and then bounced 
up a few degrees around 3 PM?</li>

<li><br /><a 
href="<?php echo BASEURL; ?>/plotting/1trace_fe.phtml?station=SPYI4&year=2003&month=10&day=8"><img 
src="solar/91_2003_10_08_1.png"></a>
 <br /><a href="<?php echo BASEURL; 
?>/plotting/1trace_fe.phtml?station=SPYI4&year=2003&month=10&day=11"><img 
src="solar/91_2003_10_11_1.png"></a> <br />Notice the different radiation 
curves for these two plots and notice the difference in the temperature.  
Can you guess what the difference between the two days is?  Notice the two 
slight increases in temperature on the second plot around 10 AM and again 
at 4 PM.  Can you tell what might have caused those increases in 
temperature?</li>

<li><br /><a href="<?php echo BASEURL; 
?>/plotting/1trace_fe.phtml?station=SROI4&year=2002&month=6&day=8"><img 
src="solar/61_2002_06_08_1.png" border="0"></a> <br /><a href="<?php echo 
BASEURL; 
?>/plotting/1trace_fe.phtml?station=SROI4&year=2002&month=12&day=9"><img 
src="solar/61_2002_12_09_1.png" border="1"></a> <br />The two plots show 
solar radiation curves for a summer day and a winter day.  Can you explain 
the differences in radiation values between the two?  Why are the values 
for summer so much higher?</li>

 </ol>

<h4>Possible Answers:</h4>

<ol> <li>The bell shaped curve is caused by the rotation of the earth and 
our local angle to the sun.  The 'bumps' in the curve during the afternoon 
are caused by fair weather clouds that occasionally scatter some of the 
sun's energy preventing it from reaching your site and the ground.  The 
events at 6 AM and 9 PM are the sunrise and sunset, respectively.</li>

<li> The roughness of the curve is explained by clouds. The amount of 
roughness can give an indication of the amount of clouds present at the 
time. For instance, the morning (till 11 AM) was probably characterized by 
thin low stratus clouds. Mid-day (11 AM till 1:30 PM) saw the development 
of larger clouds resulting in mostly overcast skies around 2 PM. The rest 
of the day probably experienced periods of clouds and sun. The temperature 
response during this time is very interesting. Notice the bump in 
temperatures at 3 PM. This was caused by the partial clearing that 
developed around 2:30 PM, that is, by the increase in solar 
radiation.</li>

<li> The two plots shown are a classic example of what happens when you 
have bright sunny days and when you have clouds. For the most part, 
temperatures will rise when more solar radiation is recieved at the 
surface. The second plot shows a day that experienced a lot of clouds 
resulting in significantly lower temperatures.</li>

<li> The difference in the maximum value of the solar radiation curve is 
can be explained by the difference in solar angle between summer and 
winter. With the sun higher in the sky, more radiation is directed toward 
the ground. With the sun lower in the sky, the solar radiation does not 
strike the ground directly and less radiation is absorbed by the 
surface.</li>

</ol>
